### ISSUE TITLE
component availability

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#100]
The assembly house verified the BOM and notified about limited availability of components:
- [x]  OSC2 OSC_EPSON_SG-310 SG-310 SCN 50.0000MJ
- [x]  OSC1 	  OSC_ONSEMI_CASE 848AB-01 	  NBVSPA019LNHTAG
- [x]  MT41J128M16HA-15E    	  IC12-IC17 	  BGA96C80P9X16_900X1400X120

**Comment by jordens** [comment]
The part choice for those is not critical from our standpoint.

**Comment by gkasprow** [comment]
I know it. I just placed here to not forget to fix it :)

**Comment by jbqubit** [comment]
@gkasprow Did you select alternate components?
@gkasprow Did the assembly house order the long lead time components for #97?

**Comment by gkasprow** [comment]
installed MT41J256M16HA-125:E
