### ISSUE TITLE
sayma_RTM precision temperature sensor

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#101]
Where are temperature sensors on Sayma_RTM? Sayma_AMC schematic includes a Thermometers block. Maybe I've missed it. In #11 @dhslichter proposed using ADT7420.

**Comment by jbqubit** [comment]
I see. It's LM75AIMM, a low performance chip (9-bit, +/-1.5 C, no long-term drift spec). We discussed on today's call. 
- [ ] do we have need for higher performance sensor on RTM (eg ADT7420)?
- [ ] what is performance of the temperatuer sensors integrated into the ADCs and DACs

**Comment by gkasprow** [comment]
they are on p.15
https://github.com/m-labs/sinara/blob/master/ARTIQ_EE/Sayma_RTM.pdf

**Comment by jbqubit** [comment]
ADT7420 proximal to ADCs and DACs. Strong thermal coupling to PCB.

**Comment by gkasprow** [comment]
done, added 2 sensors, connected to the I2C switch.
