### ISSUE TITLE
allaki: RFI filter simulation

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#104]
RFI simulation of ADC input filters on p. 3 of Allaki schematic (ADC_FE4PID.SchDoc). Discussed in #81.

**Comment by jbqubit** [comment]
@sbouhabib What's the status of this?

**Comment by sbouhabib** [comment]
![image](https://cloud.githubusercontent.com/assets/22678856/23544240/7d9b572e-fff6-11e6-82f5-02685ef7c802.png)

for discussion
