### ISSUE TITLE
allaki: Diff2SE balun choice

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#107]
Modeling is needed to make a balun choice. Target bandwidth is 10 MHz to 3.5 GHz. 
- [x] 1:1 vs 1:2
- [x] TCM2-43 is recommended by @hartytp 
- [x] placement of ~ 0.5 pF caps

**Comment by sbouhabib** [comment]
![image](https://cloud.githubusercontent.com/assets/22678856/21393643/a7362b16-c795-11e6-8f5b-d78071f8c4f1.png)

simple S11, single ended to differential test with 100 Ohm termination

**Comment by jbqubit** [comment]
Based on call today... go with TCM2-43.

**Comment by jbqubit** [comment]
Why is this issue now closed? eg TCM2-43 doesn't appear in the schematics?
