### ISSUE TITLE
allaki: analog output coupling

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#109]
@hartytp  Discussed in today's conversation. No suitable balun exists for output coupling. Instead use 100 pF series capacitor to drive SMA.

**Comment by hartytp** [comment]
> No suitable balun exists for output coupling

probably more accurate: no balun needed for output coupling

> Instead use 100 pF series capacitor to drive SMA.

between circuit ground and SMA ground for users who want isolated grounds on the output (otherwise, replace with a short).
