### ISSUE TITLE
Sayma/Metlino layout, clocking plan

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#116]
Sinara clocking plan is discussed on the wiki. https://github.com/m-labs/sinara/wiki/SinaraClocking

@jordens @sbourdeauducq Are you satisfied that Metlino and Sayma schematics are compatible with the Sinara clocking plan?

**Comment by jbqubit** [comment]
Depends on #112.

**Comment by jordens** [comment]
I checked feec424
Metlino MCH, looks good to me. Still going through Sayma AMC and RTM.

@sbourdeauducq could you verify the source of REC_CLOCK_P/N on Metlino and Sayma?

**Comment by sbourdeauducq** [comment]
REC_CLOCK (from FPGA to Si chip) can be placed anywhere.

**Comment by jordens** [comment]
Sayma_AMC and Sayma_RTM also LGTM.

**Comment by jbqubit** [comment]
Thank you Robert.

**Comment by jbqubit** [comment]
- [ ] Are you satisfied with the layout of baikal #112 with respect to the clocking plan?

**Comment by jordens** [comment]
W.r.t. to the clocking plan, Baikal distributes the 100 MHz clock to the RF backplane and Metlino-AMC. AFAICT from Baikal_rough_sch.pdf it achieves that.

**Comment by jbqubit** [comment]
@jordens @sbourdeauducq Thank you for taking a close look.
