### ISSUE TITLE
baikal test: RFB clock reflection due to unoccupied RTM slots

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#118]
First discussed in #78. 

Paraphrasing @sbouhabib
>one thing just occurred to me, the ADCLK954 has no option to turn outputs on or off, which means ,that either all outputs are on or all are off, if the whole crate is not populated, the rest are left floating which is not so nice. There may be reflections, mismatches, worse performance of ADCLK in general, higher cross-talk, unnecessary additional "noise" on the RF-backplane. 

@hartytp 
> When we have the prototype hardware, we can test whether this is actually a problem (no point complicating the circuit to fix this if it's not a problem). If the reflections do cause problems, my preferred solution would be to add an ADCLK925 (or similar) as an output buffer for each channel after the fanout buffers. These output buffers should provide sufficient isolation between the outputs.

**Comment by sbourdeauducq** [comment]
@sbouhabib Why would the reflections bother the ADCLK954? We can also add termination resistors in unpopulated slots (no PCB respin, less configuration, conceptually simpler).

**Comment by gkasprow** [comment]
As I said, we can use small MOSFETs with capacitor in parallel.
If you disconnect the pulldown resistor, no signal will be generated at the outuput.
Any idea why this solution would not work?

![obraz](https://cloud.githubusercontent.com/assets/4325054/21073578/a740f124-bee2-11e6-90ad-84d05c5904f1.png)

**Comment by hartytp** [comment]
@gkasprow AFICT that would work fine. Would the MOSFETs be controlled from a microprocessor or using DIP switches? If we use a microprocessor, is it worth adding an RC filter on OUT_EN to ensure that noise doesn't couple onto the clock outputs?

**Comment by jbqubit** [comment]
@sbourdeauducq asks "Why would the reflections bother the ADCLK954?"

The spec sheet doesn't detail output to output isolation. I think @gkasprow approach will work. Thought we agreed to use DIP switches for this type of configuration. Pads for termination resistors could be added as risk mitigation and to permit a differential test between termination vs MOSFET approach.

- [ ] add to schematic voltage supplied by OUT_EN

**Comment by sbourdeauducq** [comment]
If it's DIP switches then no mosfets are needed.

**Comment by sbourdeauducq** [comment]
But I'm skeptical we need any of this.

**Comment by sbouhabib** [comment]
the RF backplane has pins for every slot called RF-conf which we can use as enables, this means that if a board is in the slot this output will be on using what @gkasprow suggested

**Comment by sbouhabib** [comment]
the only thing left would be the 3 slots that get the CLK signals only, these cannot be controlled automatically, maybe we can leave them be, that would give us info on potential problems, while the "analog" signals throught the coax connectors are safe

**Comment by jbqubit** [comment]
It's hard to talk about this without being able to see backplane schematics #135. It's new to me that RF-conf exist. I like the idea of using RF-conf by the way. :)
