### ISSUE TITLE
PCB_MCH_mordovia

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#120]
In a Sinara crate clock distribution is done using BP_RTM/PCB_baikal; not much of the AMC Tongue 2 backplane clock distribution which is standard for uTCA.4 will be used by Sinara. Therefore NAT-MCH-CLK-PHYS is overkill for Sinara. In today's conversation WUT agreed to fabricate a very simple board that serves as a stand-in for a full-featured Tongue 2 PCB. It's called PCB_MCH_mordovia. It will be located in git at at TBD location ARTIQ_xx/MCH/PCB_MCH_mordovia. 

Checklist for this part. 
- [x] schematic
- [x] schematic design review
- [x] layout
- [x] layout design review

**Comment by gkasprow** [comment]
It is located at: ARTIQ_ALTIUM\PCB_MCH_mordovia.
Schematic and layout is here
[PCB_MCH_mordovia.pdf](https://github.com/m-labs/sinara/files/644756/PCB_MCH_mordovia.pdf)

**Comment by jbqubit** [comment]
Do we want to add 100 MHz on AMC clock fabric (PCIeCLK) to be uTCA.4 compliant?

**Comment by gkasprow** [comment]
Do we plan to use it somewhere outside of our ecosystem?

**Comment by jbqubit** [comment]
This anticipates a future where users may want to use commercial AMC cards. If you think it's best to postpone this type of support to a future revision I'm OK with that.

**Comment by gkasprow** [comment]
I simply finished the design and want to focus on more important stuff :)

>

**Comment by jbqubit** [comment]
Agreed. Keep it simple. ​

-------
Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil

**Comment by jbqubit** [comment]
Move discussion of schematic and layout from [here](https://github.com/m-labs/sinara/issues/99#issuecomment-276042586) to this Issue.
