### ISSUE TITLE
Metlino_AMC on-PCB clock input

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#122]
Per conversation today. SMA is for in-crate routing of 100 MHz clock from BP_RTM/PCB_baikal. As discussed today in #112.

**Comment by jbqubit** [comment]
This will be used for clocking Metlino FPGA in case where crate clock is derived from 100 MHz OCXO on BP_RTM/PCB_baikal.

**Comment by gkasprow** [comment]
Added SMA on the opposite side of the Metlino. Selection of clock source by capacitor placement.
