### ISSUE TITLE
test of Sayma_RTM thermal loading

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#124]
WUT thermal analysis will be per-PCB not for full system. PCB_mezzanine_clock_template and PCB_mezzanine_analog_template will be populated with heating elements to permit testing of system performance under thermal load.
- resistors
- configure resistors using MOSFET switches toggled by I2C under MMC control

**Comment by gkasprow** [comment]
Added dip switch and resistors.
For each power branch, 50% and 100% load can be selected.
MOSFETs are controlled by additional I2C extender. Manual operation is also possible.

**Comment by jbqubit** [comment]
Thank you for making the modifications @gkasprow. 
- [ ] AFE_mezzanine_3D.pdf shows misplaced meander under SMA connectors. 

This is assigned to the "0.1 testing" milestone which will take place in Jan. Reopening.

**Comment by gkasprow** [comment]
@jbqubit what do you mean by "meander" ?

**Comment by jbqubit** [comment]
Grey bit under the SMAs in the following screen shot of  AFE_mezzanine_3D.pdf. 

![image](https://cloud.githubusercontent.com/assets/20543958/21121135/b043fb60-c098-11e6-8c29-305c98b9a4bf.png)

**Comment by gkasprow** [comment]
This is a silkscreen related with footprint.
It will be removed by PCB manufacturer.

**Comment by jbqubit** [comment]
I see now. :/

-------
Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil
