### ISSUE TITLE
RF shielding of Sayma_RTM

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#126]
@gkasprow Please reiterate options we discussed in today's call. 

- [x] RF shields for clock distribution components
    - use removable lids 
- [ ] what else should be shielded
- [x] board-board isolation options

**Comment by gkasprow** [comment]
Added 3 Wurth 30x30mm boxes with removable lid. All clocking circuits  are covered
![obraz](https://cloud.githubusercontent.com/assets/4325054/21084469/8033aaa4-c004-11e6-84b4-c5c40f68651f.png)

**Comment by hartytp** [comment]
@gkasprow Looks good, so long as it won't cause a problem with thermal performance.

**Comment by jbqubit** [comment]
On Friday we also discussed metal shield fully covering the back side of each Sayma_RTM. This would provide board to board isolation. The value of this could be tested in 0.1 by comparing the performance of a rack with adjacent Sayma_RTM vs a rack with metal spacers interleaved between the Sayma_RTM. Is NAMC-Filler FS-RP1D made of metal? Can it serve as a good RF shield for tests?

**Comment by gkasprow** [comment]
Piece of steel that has no connection to ground is poor shield.
So even if you manage to insert NAMC-Filler FS-RP1D (without panel) between AMCs, it won't help much in RF shielding.
I saw somewhere (I have to ask  Pentair) complete RF shields for RTMs. And IMHO only such solutions would help.

**Comment by gkasprow** [comment]
I found covers from Schroff:
http://schroff.pentair.com/en/schroff/MicroTCA-/Module-cover-for-MTCA-4-front-and-RTM-modules
These are just mechanical protection cases, not RF cages.

**Comment by gkasprow** [comment]
I got mechanical files from Schroff.
Such case will fit, but it requires some changes to the layout
Look here:
[Sayma_RTM_shield.pdf](https://github.com/m-labs/sinara/files/664944/Sayma_RTM_shield.pdf)
In this 3D view, both solution with cage and individual shields are shown so they intersect in some places
Similar cage exists for AMC side.

**Comment by jbqubit** [comment]
> 3 Wurth 30x30mm boxes with removable lid. 

The Wurth boxes sound fine.  Closing Issue. Re-open if they pose thermal problems.
