### ISSUE TITLE
SAYMA_AMC I2C addres conflict

### ISSUE THREAD

**Issue by michallgaska** [m-labs/sinara#128]
I found address conflict between IC34 (LM75) and IC38 (MAX6642ATT90+T) on MMC_I2C in Sayma_AMC.
Both devices have address 1001000.

**Comment by gkasprow** [comment]
@michallgaska Whicz address is available for LM75? Is 1001111 OK?

**Comment by michallgaska** [comment]
1001111 in not available. 1001011 will bo ok.

**Comment by gkasprow** [comment]
fixed
