### ISSUE TITLE
Source of P6V0A

### ISSUE THREAD

**Issue by WeiDaZhang** [m-labs/sinara#132]
On ARTIQ_EE/Sayma_RTM.pdf (version v0.95), there is a P6V0A supplying the mezzanines and a few clk rails.
The source of this P6V0A, I assume, is P6V0 derived from P12V0. But this P6V0A doesn't seem to me connected to P6V0 anywhere in the schmatic. Could anyone please check that, thanks.

**Comment by gkasprow** [comment]
That's true, Filip found this issue a few days ago :)
Thanks
