### ISSUE TITLE
uTCA.4 backplane schematics

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#135]
Please add schematics for backplanes to the repository. This will make it easier to understand dependencies like activation of clock circuits as in #118. 
- [ ] PCB_BP_AMC_7slot
- [ ] PCB_BP_AMC_12slot
- [ ] PCB_BP_RTM_12slot
- [ ] PCB_BP_RTM_7slot

**Comment by jbqubit** [comment]
Can NAT or Schroff supply these for the specific part numbers we've specified for 0.1?

**Comment by jbqubit** [comment]
@gkasprow Is this info available? We need schematics of some sort so end users and testers know how to use the backplane.

**Comment by jbqubit** [comment]
@gkasprow Is this information available? If yes please attach link to this Issue and add to wiki. If not let's just close.

**Comment by gkasprow** [comment]
It's not available to my knowledge.
