### ISSUE TITLE
Sayma_RTM.pdf formating error

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#137]
Latest commit. Using Windows 7 Adobe Reader. Lots of missing annotation. 

![image](https://cloud.githubusercontent.com/assets/20543958/22255574/c1d501ea-e225-11e6-8ad5-d663d9ff4e58.png)
![image](https://cloud.githubusercontent.com/assets/20543958/22255601/d6c5c1f2-e225-11e6-84ca-f34155d57c79.png)

**Comment by gkasprow** [comment]
fixed
