### ISSUE TITLE
distribution plan for final product

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#14]
hardware distribution for final product
- work with commercial partner (eg Creotech)
  - partner responsibilities
    - collect orders, bill customers
    - build and test boards
    - distribute boards to customers
    - handle RMA's
    - maintian inventory (what size?)  
  - remuneration
    - what is reasonable markup?

**Comment by gkasprow** [comment]
In such cases the company adds 20..30% to the cost of components and
manufacturing process.
This is to cover the costs of:
- additional pieces manufacturing for warranty purposes
- testing, packaging
- support
- stock handling of long lead time parts
