### ISSUE TITLE
Sayma AMC-RTM FPGA link

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#140]
In #9 we discussed IO multiplex mechanisms for interface between Sayma_AMC FPGA with Sayma_RTM_analog_mezzanine. A decision needs to be made as to the implementation. Discuss here.

-----------

Here's a distillation of the discussion in this Issue. 

# Sayma RTM/AMC FPGA link

Initial implementation will use one AMC-RTM LVDS pair to communicate with the FGPA on the RTM. On the RTM FPGA there will be a Wishbone bus for interfacing with RTM ICs using PHY_SPI, PHY_I2C and PHY_TTL. No support for DRTIO in v0.1. Implications: 
- RTM resource access would not be synchronous with DRTIO
- Bandwidth is limited by wishbone. How much?

Future: 
- In the future, use second LVDS pair, DRTIO switch for fixed-latency/time-critical transactions.

## analog mezzanine
IO configuration mirrors discussion in #148. 
- 4 mezzanines per PCB_Sayma_RTM
- 16 IO pins per analog mezzanine
    - 4 groups of 4 IO: AM0, AM1, AM2, AM3
- let c1 be 4 of TTL_PHY 
- let c2 be 1 of SPI_PHY (uses 4 IO lines)
- AM0, AM1, AM2, AM3 each independently configurable as c1 or c2
- support for I2C

## Other
- configuration of other ICs on RTM
- bootstrapping as discussed by @sbourdeauducq below

**Comment by gkasprow** [comment]
Please notice that I upgraded I2C scheme.
Now one can configure any combination of I2C devices to be connected to MMC or FPGA.
It is possible to select one I2C device at the time or any combination of them.
The upgrade is applied to all boards.

**Comment by sbourdeauducq** [comment]
First of all DRTIO or not is independent from the type of transceiver used (GTX with CDR or IOSERDES with dedicated clock signal).

Then, the AMC-RTM FPGA link, or at least part of it, has to be up and running before DRTIO. This is because the clock chips that are required for DRTIO must be configured over the link. For this, we will use a Wishbone-over-serial bridge that will give the AMC CPU access to the SPI core on the RTM side and let it do transactions on the converter SPI bus.

If required, we could use one AMC-RTM LVDS pair for Wishbone, and the second that we have could be clocked synchronously to DRTIO for fixed-latency/time-critical transactions. Since we have only one Si5324, [this scheme](http://www.xilinx.com/support/documentation/application_notes/xapp589-VCXO.pdf) can be used on the Wishbone pair where phase noise (and fixed latency, since this scheme precludes GTP TX buffer bypass) is less important.

**Comment by jbqubit** [comment]
>"we will use a Wishbone-over-serial bridge that will give the AMC CPU" 

By "AMC CPU" do you mean the AMC soft-core uP in the FPGA? I didn't think m-labs was using the AMC-side hardcore uP (LPC1776, Cortex-M3). 

Once bootstrap over has completed (using RTM_FPGA_LVDS1,2) communication with the RTM-FPGA will be via DRTIO using transceivers (RTM_FPGA_GTP_Rx0,1), right?  

Is the IO performance plausible?

**Comment by sbourdeauducq** [comment]
Softcore uP. Everything over GTP. DRTIO is possible if desired, but needs support for switches and different data rates in the same system.

**Comment by jbqubit** [comment]
Is is reasonable to start with a simple approach and upgrade in the future to DRTIO when [DRTIO switch](#619) becomes available? That is is #619 a hard dependency?

**Comment by sbourdeauducq** [comment]
Start with a simple approach for doing what exactly?

**Comment by jbqubit** [comment]
Initial implementation using one AMC-RTM LVDS pair to communicate with Wishbone bus RTM. SPI, I2C and TTL PHY's attach to the Wishbone bus for control of  RTM peripherals. I can't well gauge the relative simplicity of this approach. I believe some of the implications vs full DRTIO switch are the following. 
- RTM resource access would not be synchronous with DRTIO. 
- Bandwidth is limited by wishbone. How much? 
Are there others relative to IO Performance mentioned in opening post? 

In the future, use second LVDS pair, DRTIO switch for fixed-latency/time-critical transactions.

**Comment by sbourdeauducq** [comment]
Again, this isn't only about simplicity or performance, the Wishbone link (or something equivalent) is made necessary by the clock chips on the RTM side which need to be running before DRTIO can work at all.

**Comment by jbqubit** [comment]
OK. Let's proceed with the simple approach for v1.0 of Sinara hardware support. The implication of this is that real-time signals will not be available on the RTM side until the [DRTIO Switch](https://github.com/m-labs/artiq/issues/619) is developed.

**Comment by jbqubit** [comment]
@sbourdeauducq Do you have enough information to generate a quote for this feature?

**Comment by jbqubit** [comment]
Mirroring discussion in #148, I propose the following gateware configuration options for the analog mezzanine IO. 

- let c1 be 4 of SERDES_TTL_PHY (or 4 of TTL_PHY if DRTIO Switch is unavailable)
- let c2 be 1 of SPI_PHY (uses 4 IO lines)

Each analog mezzanine has 16 general purpose IO. Proposed configuration is 
- 4 groups of 4 IO: AM0, AM1, AM2, AM3
- AM0, AM1, AM2, AM3 each independently configurable as c1 or c2

Additional IO for each analog mezzanine: I2C.

**Comment by jbqubit** [comment]
@dhslichter @dtcallcock @sbourdeauducq Any comments on my proposal from three days ago? If this is satisfactory I'll update leading post.

**Comment by dhslichter** [comment]
These two configuration options, and being able to choose configurations in blocks of 4 IO as described, sounds good to me.  I2C is a separate entity.

**Comment by jbqubit** [comment]
I updated the leading post to this Issue with a distillation of what I believe is the consensus. I'm closing the Issue as there don't seem to be unresolved questions. Please reopen if I'm mistaken.
