### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#15]
We should have logo(s) on the PCB silkscreen and the panels. I propose simply the ARTIQ logo (https://github.com/m-labs/artiq/tree/master/doc/logo). Any other ones or alternatives?

**Comment by gkasprow** [comment]
Do you have it in dxf/dwg form?

**Comment by gkasprow** [comment]
Well, it doesn’t open for some reason.

But I was able to open pdf with Inkscape and convert it to dxf which can be used by CAD tool.
