### ISSUE TITLE
wrong stackup height for Sayma RTM, clock mezzanine, analog mezzanine

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#151]
I found that stacking height of SAMTEC_LSS-120-03-L-DV-A connector was wrong.
It is 8 mm while it should be 9mm
http://suddendocs.samtec.com/catalog_english/lss.pdf
Theoretically this should work like it is now, but let's do it properly.
So I replaced SAMTEC_LSS-120-03-L-DV-A on RTM board with SAMTEC_LSS-120-02-L-DV-A
The clock and analog modules now have SAMTEC_LSS-120-01-L-DV-A
@sbouhabib please update connector on your module accordingly. The correct version is in reference designs.

**Comment by jbqubit** [comment]
@gkasprow Is this resolved? If so close Issue.

**Comment by gkasprow** [comment]
Samer must close it after he modifies his board.
