### ISSUE TITLE
I2C tree

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#159]
I added on Sayma/Metlino top entity simplified I2C connectivity with chip numbers and addresses. 
Is such drawing clear enough?
Sayma
![obraz](https://cloud.githubusercontent.com/assets/4325054/22908472/f4c57eca-f24e-11e6-93f8-926583ee143c.png)

Metlino
![obraz](https://cloud.githubusercontent.com/assets/4325054/22908491/0a4cb77c-f24f-11e6-9cdc-36cdf771b8aa.png)

Don't be surprised by the fact that MMC is able to modify MUX address. This is to mitigate future problems where I2C address conflict occurs. Simple MMC firmware update will solve it.
Another new feature is double mux access to the same peripherals (from MMC and FPGA). We can configure I2C  tree on startup or in any moment.

**Comment by jbqubit** [comment]
Looks good... Some comments. 
- Metlino MUX Port 6/7 right-hand-side blue box should be "VHDCI" not "RTM ports"
- on PCB_Sayma_RTM each analog mezzanine has one I2C
    - allaki I2C chips #144

**Comment by gkasprow** [comment]
@jbqubit what do you mean that "on PCB_Sayma_RTM each analog mezzanine has one I2C " ?
Do you mean one I2C interface

**Comment by jordens** [comment]
@gkasprow IMHO the most useful representation would be textual, machine and human readable. In the end, it will need to be machine readable anyway.

Something like this (for Sayma):

```json
{
  "AMC_MUX": {"path": [], "addr": 0x71},
  "FMC_EEPROM": {"path": [0], "addr": 0x50},
  "SFP1_EEPROM": {"path": [2], "addr": 0x50},
  "SFP1_DDMII": {"path": [2], "addr": 0x51},
...
  "AMC_SI5324": {"path": [4], "addr": 0x68},
...
  "AMC_MAX6642": {"path": [6], "addr": 0x24},
...
  "RTM_MAX6642": {"path": [7], "addr": 0x24},
  "RTM_MUX": {"path": [7], "addr": 0x76},
  "AFE0_TCA9539_0": {"path": [7, 0], "addr": 0x74},
  "AFE0_TCA9539_1": {"path": [7, 0], "addr": 0x75},
  "AFE0_LM75": {"path": [7, 0], "addr": 0x48},
  "AFE0_24AA02E48": {"path": [7, 0], "addr": 0x50},
  "AFE1_TCA9539_0": {"path": [7, 1], "addr": 0x74},
...
  "RTM_SI5324": {"path": [7, 5], "addr": 0x68},
...
}
```

**Comment by jbqubit** [comment]
> what do you mean that "on PCB_Sayma_RTM each analog mezzanine has one I2C "

In schematic for Mezzanine_connectors1 I2C_SDA is connected to MEZ_SDA4. I don't see the analog Mezzanine connectors' I2C in your map.

**Comment by gkasprow** [comment]
@jbqubit you are right, I modified the schematic to keep the convention. 
The second table describes connections of mezzanines. I changed AFE to Analog mezzanine to keep naming consistent.
