### ISSUE TITLE
mailing list vs Issue system

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#160]
This is a recurring theme.  I believe it is resolved. To keep technical Issues on topic, reference this Issue if there is further need to discuss what goes in mailing list vs Issue system. 

@sbourdeauducq in #141
> This should not be in a issue tracker, and especially not one for the hardware. I think the mailing list is a better place to brain storm and discuss specifications; the latter can be located in a wiki (the ARTIQ one is appropriate in this case). Again, issues are for single actionable items.

@sbourdeauducq in #150 
> @hartytp I think the mailing list would be a better place for this discussion.

@hartytp says in #150 
> I'd prefer to keep the discussion here for now unless you really feel strongly about it? IMO, the amp board is a relevant piece of support hardware for the Sayma/Kasli DDS boards being developed here. So, this is a natural place to have the discussion. Also, my impression is that the followers of this Git Hub project are a good representation of the sub-set of the Artiq list readers who are interested in hardware development.

@sbourdeauducq in #150 
> Well, GitHub issues are more appropriate for actionable items than for discussions or asking questions around.

@hartytp in #150 
> I know this isn't really what the issue tracker is for. But, it does work very well, so can we go on abusing the system a while longer ;)

@sbourdeauducq in #150 
> I'm pretty sure the mailing list would work just as well, e.g. all the participants in this issue are subscribers.

@jbqubit in #150
> I advocate for using the Issue system as we are in this Issue. Downsides of mailing list AFAICT 
- ditribution includespeople who don't care about Sinara-Kasli related hardware
- @mention, #issue auto-linking isn't available
- no wiki for pulling together ideas
- inclusion of inline images is unpleasant
- single-page viewing of conversation thread is not supported
- Markdown isn't supported

@hartytp in #150
> @sbourdeauducq I can re-cast this in issue format if that helps: nebulous discussion thread => issue: specify this hardware, close when specification agreed.
> Edit: but, I do take your point. Next time I want to ask a question like "is anyone interested in ..." I'll post to the list.

**Comment by sbourdeauducq** [comment]
> #issue auto-linking isn't available

You can paste issue URLs.

> no wiki for pulling together ideas

Same with issues.

> single-page viewing of conversation thread is not supported

It is if you use e.g. gmail.
