### ISSUE TITLE
PCB_Sayma_RTM thermal

### ISSUE THREAD

**Issue by michallgaska** [m-labs/sinara#162]
I did Sayma_RTM thermal simulation. I assumed 10m3/hr air flow. 
I added small heatsinks on LTM4619.
I was trying to simulate Sayma_RTM with mezzanine cards  (I don't have proper design so I only assumed power dissipation) but I had some errors. I reported it to Mentor Graphics and now I am waiting for the response. 
If it will be necessary we can make custom heatsink for DACs or place heatsink on the other side of the board. 

![sayma_rtm_thermal_heatsink](https://cloud.githubusercontent.com/assets/18462070/23162171/30abbd4e-f82d-11e6-9f9c-7a7cc32304ce.jpg)

**Comment by hartytp** [comment]
Nothing to do here, so closing (please open a new issue for anything to do with characterisation of prototypes etc).
