### ISSUE TITLE
Sayma Signal Integrity

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#166]
I'm trying to optimize JESD signal chain.
I use HL9.4.1, models for GTX, all connectors and DAC.
Here is how the eye diagram looks like without optimisation and via matching

![obraz](https://cloud.githubusercontent.com/assets/4325054/23549510/e60fd1f2-000c-11e7-91aa-d33755f4d295.png)

And with matched vias and optimised traces

![obraz](https://cloud.githubusercontent.com/assets/4325054/23549526/f3e6a86e-000c-11e7-9ddf-f5e1894d85c3.png)

but still I cannot meet BERR requirement, even using FR408 PCB material
it seems that I have to experiment with other trace widths - there is always trade-off between skin effect losses and dielectric losses.
So  without pre-emphasis on the Tx side the eye diagram looks like this:
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550373/c6647c96-0010-11e7-8783-d5ece0b29358.png)

With simulated 3-tap  pre-emphasis  BERR is 3e-8
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550409/f07ae434-0010-11e7-831c-8cf491a802f7.png)
5-tap gives BER=9e-14 assuming  jitter = 1% of UI
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550485/634c4b60-0011-11e7-9608-a0d8d092340c.png)

So theoretically we meet JESD204B requirements, but the question is how GTX pre-emphasis has to do with HL simulation and how many taps the GTX has.
I took eye diagram mask from this [presentation](https://www.slideshare.net/AnalogDevicesInc/jesd204-april2012)

**Comment by gkasprow** [comment]
I can specify GTX taps/parameters, simulation was made with "synthesize optimal values" option enable.

**Comment by gkasprow** [comment]
Here is bathtub plot
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550705/b78bd492-0012-11e7-969f-1c25f9067b0d.png)
Some JESD204B specify mask at 55mV like [here](http://archive.eetasia.com/www.eetasia.com/ART_8800685415_499501_TA_28e33ab7_3.HTM)
Our DAC specifies eye mask 
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550825/55d6cbfc-0013-11e7-9fea-6d37c4e9a5c4.png)
So if we apply its settings we get (without pre-emphasis and with 1% UI jitter)
![obraz](https://cloud.githubusercontent.com/assets/4325054/23550868/9e34f892-0013-11e7-8fb1-0eb1b54aa798.png)

**Comment by gkasprow** [comment]
So the question is - shall I continue to meet JESD204B channel specification or we should only satisfy our DAC :)

**Comment by jordens** [comment]
A few questions from my side:

* How do the dB values of pre-emphasis in the GTH transcievers relate to the tap numbers you are working with?
* Can you localize the cause for the degradation? The long traces, impedance steps due to corners/proximity, non-linearities/losses in the material, or is it the connector?
* What about the ADC JESD link?

**Comment by gkasprow** [comment]
A few questions from my side:
>
>    - How do the dB values of pre-emphasis in the GTH transceivers relate
>    to the tap numbers you are working with?
>
> This is a question I want to ASK. I don't know GTX/GTH transceivers in
such detail


>
>    - Can you localize the cause for the degradation? The long traces,
>    impedance steps due to corners/proximity, non-linearities/losses in the
>    material, or is it the connector?
>
> I removed piece by piece parts of my model and it seems it is combination
of all these components.
This simulation is after optimisation of transmission channel

>
>    - What about the ADC JESD link?
>
> It is the same model, didn't analyse it yet. The speed rate is much slower
so I don't expect any issues.

**Comment by gkasprow** [comment]
And here is the model extracted from both PCBs
![obraz](https://cloud.githubusercontent.com/assets/4325054/23554722/91a1802e-0026-11e7-850d-282abd6184da.png)

**Comment by gkasprow** [comment]
For ADC channel running at 8Gbps I do not observe any issues. With 1% UI jitter, no pre-emphasis I got perfect plot
![obraz](https://cloud.githubusercontent.com/assets/4325054/23555367/efba0530-0028-11e7-8b81-a8f49ce48b89.png)
![obraz](https://cloud.githubusercontent.com/assets/4325054/23555379/ff9deb2e-0028-11e7-8b29-25309f5ef824.png)

**Comment by gkasprow** [comment]
Even with standard JESD204B mask BER is 7.7e-13
![obraz](https://cloud.githubusercontent.com/assets/4325054/23555432/3a242f42-0029-11e7-8777-77881dd26c28.png)

**Comment by jordens** [comment]
@gkasprow sorry for the confusion. To (re)confirm: we only need 10 Gb/s lane rate (not 12.5 as I said) for the DACs. You can choose from your experience what margin you add to that. But the base rate is 10 Gb/s (for 1 GHz sample data rate).

**Comment by gkasprow** [comment]
@jordens that's great. I did analysis for 14G and it looked very bad.

**Comment by abyszuk** [comment]
GTH transceivers allow for directly setting pre/post-emphasis in [dB] units.
PREcursor has (0; 6.02) dB range with 20 steps.
POSTcursor has (0; 12.96) dB range with 31 steps.

Number of filter taps is defined only for RX path.

**Comment by jbqubit** [comment]
@gkasprow Is this Issue now resolved? If so please close.
