### ISSUE TITLE
name DDR3_64_CE0_N consistently

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#171]
* this signal is usually called CS_N
* the 32-bit DDR uses the usual name DDR3_32_CS_N

**Comment by gkasprow** [comment]
We have two DDR controller so have to distinguish names for 32bit and 64bit
ones.
We have another CS_N signals so they cannot be called the same.

**Comment by sbourdeauducq** [comment]
There is this problem on every other signal and it is solved by prefixing by DDR3_32_ and DDR3_64_.

**Comment by gkasprow** [comment]
OK, I got what you mean:)
