### ISSUE TITLE
remove note about "LVDS, 1.8V" in 3U_VHDCI_Baseboard

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#173]
LVDS is LVDS, regardless of the FPGA bank supply voltage.

**Comment by gkasprow** [comment]
This is true providing that you use only LVDS
If you configure FPGA by chance in LVCMOS mode, then supply voltage matters
and the receiver must handle it. Otherwise latch-up can occur and receiver
can be destroyed.

**Comment by sbourdeauducq** [comment]
OK. Then I think it should say "LVDS or LVCMOS18".

**Comment by gkasprow** [comment]
done, also changed in note on Metlino schematics.
