### ISSUE TITLE
directory organization

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#175]
Individual hardware projects are organised into directories, sorted first by the CAD tool used and then by the project hierarchy. Projects developed in Xpedition are stored in the ARTIQ_EE directory, while Altium projects are stored in the ARTIQ_ALTIUM directory. 

Is this really a sensible way of organising things? Wouldn't it be better to just sort by the project?

**Comment by gkasprow** [comment]
Xpedition schematic projects need to be in same directory because they
share same database.
Altium projects can be placed in any suitable hierarchy.
Propose something and I will adopt my directory structure.

**Comment by sbourdeauducq** [comment]
OK, fine then.
