### ISSUE TITLE
Allaki - AD8253

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#180]
@sbouhabib, it seems that there is wrong connection of WRn signal.
It is referenced to DGND and accepts TTL levels. Now it is connected to -12V and it is out of the IC range.
Should be tied to GND.

**Comment by jordens** [comment]
That's how you enable transparent gain setting mode. It's fine.
See [Figure 53](http://www.analog.com/media/en/technical-documentation/data-sheets/AD8253.pdf#page=17).
