### ISSUE TITLE
Allaki: R and C errors

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#181]
@sbouhabib C34 and C41 are rated for 10V while connected to 12V

**Comment by gkasprow** [comment]
@sbouhabib there is a stub in RF chain.
![obraz](https://cloud.githubusercontent.com/assets/4325054/26253645/5e65bb42-3cb4-11e7-93ea-89e33b23e075.png)

**Comment by gkasprow** [comment]
@sbouhabib The bias resistor for ERA-4XSM+ seem to have too low power.
If we take recommended bias current of 65mA at 12V supply it gives 0.4W. 0402 resistor won't handle it.

**Comment by jbqubit** [comment]
Please create independent Issues for different bugs. I moved stub to new Issue.

**Comment by sbouhabib** [comment]
Both issues fixed
