### ISSUE TITLE
Sayma DDR3 ASIC not labeled

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#184]
In #178 it was determined to use MT41K256M16TW-107:P in Sayma. The Sayma_AMC and Metlino_MCH schematics do not reference this part number. 

@gkasprow Is this 32 Meg x 16 x 8 banks = 4096 Mega bit or byte? Please also add to schematic.

**Comment by hartytp** [comment]
@gkasprow Is this done? Can we close this?
