### ISSUE TITLE
8 channel Power amplifier protection circuit schematic review

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#186]
@hartytp I sketched schematic of the control & protection board [(link)](https://github.com/m-labs/sinara/blob/master/ARTIQ_ALTIUM/PA_8CH/PA_8CH_CTRL.PDF). It is still early version, the physical layout will change once the mechanic design is ready.

**Comment by hartytp** [comment]
Thanks for posting that @gkasprow!

That all looks good to me so far -- although, I don't have the expertise required to give you detailed feedback on this design.
