### ISSUE TITLE
github handles

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#19]
Who is involved in Sinara/Kasli development? 
- Name, Email, GitHub ID

__m-labs__
- Robert Jordens, jordens
- Sebastien Bourdeauducq, sbourdeauducq
email addresses: (rj, sb) at m-labs.hk 

__NIST Boulder__
- physicist, Daniel Slichter, dslichter ((at)) gmail.com, dhslichter
- physicist, David Allcock, ,dtcallcock

__UMD__
- physicist, Jason Amini, amini ((at)) umd.edu, jasonamini
- physicist, Johnathan Mizrahi, jmizrahi

__ARL/UMD__
- physicist, Joe Britton, joe.britton.arl ((at)) gmail.com, jbqubit

__Warsaw WUT__
- team lead is Grzegorz Kasprowicz, kasprowg ((at)) gmail.com,  gkasprow
- analog/RF lead is Samer BouHabib, samerbouhabib ((at)) gmail.com, sbouhabib 
- FPGA lead is Wojciech Zabolotny, wzab01 ((at)) gmail.com, wzab
- project graduate student is Michał Gąska, michalgaska2 ((at)) gmail.com, michallgaska 
- documentation and schematic review, Filip Świtakowski, switakowski.filip ((at)) gmail.com, filipswit
- Kasli schematic+layout, Pawel Kulik, P.P.Kulik((at))stud.elka.pw.edu.pl , marmeladapk 

__Warsaw Creotech__
- Team leader, Marcin Kiepiela, Marcin.Kiepiela ((at)) creotech.pl, mkiepiela
- FPGA specialist, Marek Gumiński, Marek.Guminski ((at)) creotech.pl, mguminski
- Procurement leader, Mariusz Mróz, Mariusz.Mroz ((at)) creotech.pl, mmroz88
- FPGA specialist (gigabit stuff, verification), Adrian Byszuk, Adrian.Byszuk ((at)) creotech.pl, abyszuk
- Testbench & MTCA specialist, Krzysztof Macias, Krzysztof.Macias ((at)) creotech.pl, km-cti

__Oxford__
- physicist, Tom Harty, hartytp
- physicist, Chris Ballance, cjbe
- electrical engineer, Weida Zhang, weida.zhang ((at)) eng.ox.ac.uk, WeiDaZhang

**Comment by jbqubit** [comment]
@jordens How do I add users to the project? Jason Amini's handle is jasonamini.

**Comment by jordens** [comment]
We'do that. But the others need to be contacted. Do you do that?

**Comment by jbqubit** [comment]
@jordens please add cjbe and weidazh and jasonamini

**Comment by jbqubit** [comment]
@Jordens please add @hartytp

**Comment by michallgaska** [comment]
Hello everyone!

**Comment by jordens** [comment]
@jbqubit all(ready) added. It seems redundant to update this issue.
Everyone: you need to accept that invitation link.
Everybody else, just ping me.

**Comment by jordens** [comment]
@michallgaska hello, https://github.com/m-labs/sayma/invitations

**Comment by dtcallcock** [comment]
@jordens can you invite me please (@dtcallcock)

**Comment by jordens** [comment]
@dtcallcock sure. done

**Comment by jbqubit** [comment]
@gkasprow fill in blank
- documentation and schematic review, NAME, EMAIL, @filipswit

@jordens invite @filipswit

**Comment by jordens** [comment]
@jbqubit people should just fill in their metadata in their profiles instead of duplicating it here where it will rot.

**Comment by jbqubit** [comment]
@jordens I'm not aware of a github mechanism that aggregates handles, emails, locale and project roles in a single location. Please tolerate the present use of #19 for purposes of the Sinara project.

**Comment by jbqubit** [comment]
@filipswit is now added. Issue closed. 

@filipswit welcome to the project!

**Comment by gkasprow** [comment]
@sbourdeauducq please change email address of Pawel Kulik to P.P.Kulik@stu.elka.pw.edu.pl

**Comment by jbqubit** [comment]
@gkasprow please add Creotech

**Comment by gkasprow** [comment]
@sbourdeauducq please add Creotech guys

**Comment by sbourdeauducq** [comment]
done

**Comment by sbourdeauducq** [comment]
Also let's try to reduce the abuse of the GitHub issue tracker. https://github.com/m-labs/sinara/wiki/Team
