### ISSUE TITLE
Urukul LEDs

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#197]
from @gkasprow:
What front panel LEDs should indicate?

* RF switch positions
* user defined functions (routed to TTL register)
* Overtermperature / Power Good
* AD9910 PROFILE, OSK

**Comment by jordens** [comment]
* the four RF switches' positions
* four further LEDs controlled by the other four lines from that 8 bit shift register.
* if there is space: overtemperature/power good.

**Comment by gkasprow** [comment]
@jordens OK, I updated wiki
