### ISSUE TITLE
phaser2 features

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#2]
These are beyond the items in #1 and would be developed on the final hardware. Individual items will be split out into separate issues and referenced here when imminent.

Short term:
- [x] Absolute and relative phase modes for all frequency and phase interpolators independently configurable through RTIO
- [ ] f,p,a,u modulation by RTIO (eDRTIO) for all interpolators
- [ ]  DMA m-labs/artiq#553
- [ ] distributed DMA
- [x] Parallelizing CIC interpolator/AA filter before parallelized DDS core
- [x] Parallelized FIR filter after CIC, research and implement what’s possible given DSP resources
- [ ] Coherent phase mode (implemented in kernel API and runtime) for frequency/phase updates of the three eDRTIO channels
- [ ] gate-able counter TTL input RTIO channel m-labs/artiq#564

Longer term:
- [x] Time stretcher for interpolators to extend dynamic range beyond spline knot durations of 2**16 cycles
- [x] Saturating summing junctions
- [ ] f,p,a,u modulation by external data stream (ePID) for all interpolators
- [x] Summing junction clipping detectors and their remote readout
- [x] Configurable, saturating output limiters
- [ ] Monitoring support for all spline interpolators and total DAC output
- [ ] Injection/override support for all spline interpolators
- [ ] Distributed hardware logic analyzer support for all interpolators and DAC output
- [ ] ADC support (ARTIQ, gateware, some DSP)
- [ ] ADC burst acquisition via DRTIO
- [ ] PID https://github.com/jordens/redpid https://github.com/nist-ionstorage/digital-servo #24

**Comment by dhslichter** [comment]
For confirmation: will DMA as listed above include the streaming of precompiled DAC samples from memory onto the DACs vias JESD204B?  This would allow for sequences that may not be able to be created efficiently by the gateware CORDIC+interpolators (e.g. 20 ns duration Gaussian pulse at 1 GSPS).  Will DMA be able to seamlessly take over streaming of DAC samples from CORDIC+interpolators, and then seamlessly return it?  Use case would be to output a fixed dc level ("off" to a mixer IF port), then briefly stream in a complex/high-speed pulse such as above, then return to fixed dc level (again, "off" to a mixer IF port).

**Comment by jordens** [comment]
Not currently. And DMA is functionally orthogonal to sample-based operation.
If somebody is interested in this (or other additional features), please open new issues.

**Comment by jbqubit** [comment]
@jordens please remove for-contract label since this is funded by ARL

**Comment by jordens** [comment]
@jbqubit not all of it.

**Comment by jbqubit** [comment]
@jordens Please annotate which parts are not funded.

**Comment by jordens** [comment]
@jbqubit that's not wise and would be redundant. the individual tracking issues should also track their funding status.

**Comment by jbqubit** [comment]
Closed since  gateware Issues migrated to ARTIQ #236
