### ISSUE TITLE
Hardware design tasks

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#20]
schematics
- [ ] Sayma AMC
- [ ] Sayma RTM
- [ ] Sayma analog mezzanines
  - [ ] baseband (<500 MHz input/output) mezzanine "Allaki"
  - [ ] microwave (to 3.6 GHz output, <500 MHz input) mezzanine "Larry"
  - [ ] up/down converting mezzanine with external LO "Moe"
  - [ ] upconverting mezzanine (output) w/ baseband inputs "Shemp"
- [ ] Sayma Oxford clock mezzanine
- [ ] Sayma WUT simple clock mezzanine
- [ ] RTM backplane Slot 15 (eRTM15) clock distribution
- [ ] RTM backplane power module (RTM-PM)
- [ ] Metlino AMC (Tongue 3-4)
- [ ] Metlino clock (Tongue 2)

---
- [ ] initial PCB placement and mechanical details
- [ ] schematics review
- [ ] simulation of PDN
- [ ] SI simulation of critical links
- [ ] RF simulation of analog chain

---
- [ ] layout of digital part of Sayma
- [ ] layout of RTM part of Sayma

---
- [ ] PDN simulation of layout (AC & DC)
- [ ] DDRs simulation of layout
- [ ] SI simulation of critical links
- [ ] EMC simulation of whole board
- [ ] PCB proto delvered

---
- [ ] DC levels
- [ ] Functionality – configuration of FPGA, access to all resources (I2C, SPI)
- [ ] Clock distribution
- [ ] SDRAM operation with Xilinx reference design
- [ ] JESD links operation with Xilinx reference design

---

Feel free to 
- break out into smaller issues and reference them here.
- reassign smaller issues
- indicate which items/questions are urgent
- close issues when resolved

**Comment by dhslichter** [comment]
I would break out schematic/layout tasks to include analog mezzanines as well.

**Comment by jbqubit** [comment]
Closing since nobody used this Issue.
