### ISSUE TITLE
Kasli power

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#203]
From @dtcallcock:

* Can we use thread-lock barrel connectors on the boards?  These are much more robust in a lab setting and are backwards-compatible with non-locking plugs for those that don't care.  Example parts are [connector](http://www.digikey.com/products/en?keywords=sc1472-nd) and [plug](http://www.digikey.com/product-detail/en/switchcraft-inc/761K/SC1148-ND/241919).

* I'd handle the 12V barrel connector for Kasli the same way you do for the VHDCI breakout, i.e. alternative. If the DIN connector is fitted, the 12 V should be provided from the backplane.

**Comment by hartytp** [comment]
@gkasprow Can we have a power budget as well, please?

**Comment by hartytp** [comment]
[ ] @gkasprow Please can you change the power connector on the VHDCI carrier to match Kasli?

**Comment by hartytp** [comment]
- [ ] Once we've finalised the number of IDCs on Kasli (including the backplane ones), we should make sure that we've properly specified the maximum +12V current that each IDC can draw, and that the power distribution network on Kasli (connectors etc) can handle the total current requirements of all IDCs/EEMs.

**Comment by gkasprow** [comment]
I planned to change it some time ago but missed it somehow.

**Comment by hartytp** [comment]
done
