### ISSUE TITLE
RJ45 LVDS breakout version 1 errata

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#218]
- swap RJ45 connectors
- place LEDs 2.1mm closer to the panel
- add GND and i2C testpoints
- add PWR LEDs
- swap pins 4 and 5 in RJ45 connector to keep compatibility with Ethernet cabling
- add TVS protection diodes

**Comment by gkasprow** [comment]
All issues fixed in rev 1.1

**Comment by jbqubit** [comment]
Thanks!
