### ISSUE TITLE
FMC DIO 32ch LVDS is missing screw

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#232]
The FMC to VHDCI adapter shipped by Creotech to UMD is missing the pair of nuts customarily on boards (circled in image). Please update the BOM to include this part. AFAICT it's not included in MOLEX_71430-0013. I've found nuts locally in a junk drawer to use with my adapter. 

![image](https://user-images.githubusercontent.com/20543958/28139055-de8bad90-6720-11e7-9dbb-e51728fbb781.png)

Including a pair of stand-offs and 4 screws for attaching the FMC side would be one less thing for end users to source.

**Comment by dhslichter** [comment]
+1 on the FMC standoffs and screws, that is great to include with any FMC daughtercard...

**Comment by gkasprow** [comment]
Joe, these are not the boards I tested and let the guys to ship to you
Mine were brown and had 32 channels, these are some old 8channel versions
that should never go to client.
And the boards I tested had both screw.
I'll explain it.
Greg

**Comment by jbqubit** [comment]
They sent four copies of the following board.

![image](https://user-images.githubusercontent.com/20543958/28139972-6d864570-6724-11e7-90b2-1931d8567f08.png)
![image](https://user-images.githubusercontent.com/20543958/28139979-7a6e6ed4-6724-11e7-9d1c-94952263a52a.png)

**Comment by jbqubit** [comment]
I had pasted an image from OHWR and circled the missing screw since I didn't have a camera handy. The boards Creotech sent are fully stuffed as illustrated in the two photos in the previous post.

**Comment by gkasprow** [comment]
OK, these boards are fine, I tested them and did this little modification
to fit pinout of Metlino/VHDCI carrier.
I thought they were brown, sorry, my fault.
The one you shown to me is different because has only 8 channels assembled.
Greg

**Comment by gkasprow** [comment]
OK

**Comment by hartytp** [comment]
@gkasprow Is this being handled by Creotech? If so, can we close this issue?
