### ISSUE TITLE
SMA DIO rev2 Errata

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#240]
- [x] Change ordering of SMA outputs on to be monotonically increasing.
- [ ] move the bank direction LEDs to the end (rather than in the middle)
- [ ] Space permitting, move the bank direction LEDs to the end (rather than in the middle). If this will reduce the pitch between adjacent SMAs too much (i.e. to the point where they get awkward to do up) then don't worry about it.
- [x] Add 100k resistors between the isolated grounds and the main circuit ground. This will prevent the boards from charging up, which could damage sensitive instruments connected to them.
- [x] all channels should be set to inputs at power-on to avoid power-on glitches associated with the option-couplers
- [x] Zero-index all channels
- [ ] Increase SMA openings in panel to 8mm
- [x] RA SMA is not available anymore, replace with  RF2-49B-T-00-50-G-HDW
- [x] Invert/fix footprints of 0603 LEDs
- [x] Please remove the annotation "This module connects to Kasli ..." and replace it with something like "EEM connector: IO are LVDS, I2C is 3V3 LVCMOS, P3V3_MP up to 20mA, P12V up to 1A."
- [x] connect EN2 of IC44/IC50 with direction control
- [x] Consider adding an LC filter to reduce the output noise
- [x] Add capacitor to reduce output noise (same as BNC board)
- [x] Switch to same DC/DC converter as the BNC board?
- [ ] Pull back the angled through-hole SMA by ~0.8mm. Simplifies board outline and makes them flush with the straddling connectors.
- [x] Add source termination resistor (something like 30R to 40R) between output driver and switchable termination.
- [x] Silk + schematic + panel should be "v1.x" not "rev1.x"
- [x] add insulating washers to the BOM

**Comment by jordens** [comment]
* [ ] SMA clearance to panel is too small
* [ ] SMA connector clearance to mounting brackets and screws is too small

**Comment by jordens** [comment]
@gkasprow Also, from my boards, only the SMA boards were shipped with corrugated washers under those screws (PCB to mounting angle block). That makes the underside of the PCB thicker than allowed and collides with the left adjacent front panel. Don't know from the top of my head whether these are supposed to use washers but it needs to be (a) consistent among all boards and (b) be below the ~2.27 mm allowed max protrusion on that side.

**Comment by gkasprow** [comment]
well, such washers were probably attached to Schroff mounting kit. The [manual](https://schroff.pentair.com/wcsstore/ExtendedSitesCatalogAssetStore/PentairDataLoad/EPSMedia/ASIM/webcat/subgroup/mi/60817-182.pdf) says they should be there. Probably I used wrong ones. The kit contains much more components than are needed :)

**Comment by jordens** [comment]
Also what does the QC sticker actually mean? On my 3U_DIO_RJ45 two pins of the RJ45 cage were not soldered.

**Comment by hartytp** [comment]
@gkasprow Should this have the same PSU as the BNC DIO board? Wasn't there a reliability issue with the SMPS you're using on this board?

**Comment by gkasprow** [comment]
I replaced these DC/DC converters with different type ones on the boards that were shipped. 
SMA DIO design was already modified to support Murata converter

**Comment by hartytp** [comment]
@gkasprow Okay, good.

I just asked because I saw the photos that Robert posted https://github.com/m-labs/sinara/wiki/EEM_SMA which have the old converter. But, maybe this was just an older revision of the pcb...

**Comment by gkasprow** [comment]
@hartytp It looks like old one but model is different. I installed one with twice higher current.

**Comment by jordens** [comment]
Even with the more powerful ones, the claim that the "outputs can supply 5V into 25Ohm" is at the very least misleading, because that would be 800 mA per 5V rail. And "tolerate an indefinite short-circuit to ground" only makes sense if it includes the DC/DC converters shutting down. Could someone clarify what is actually meant by those statements?
And why did technosystem distribute rev1.0? Should I send them back?

**Comment by hartytp** [comment]
@gkasprow Thanks for the update! But, I'm confused, should these have the Murata converter or the higher current rated Traco power one?

**Comment by hartytp** [comment]
@gkasprow PS, not sure if I already said this, but: I set a rack up in my lab like the one Robert posted photos of. Modulo the small bugs we've posted, it all works really nicely and looks great! Thanks again for all the great work you guys have done on this.

**Comment by gkasprow** [comment]
The SMA version is v1 but with higher power dc/dc converter. Murata is same power.

**Comment by gkasprow** [comment]
@jordens do you insist on adding supporting insulating washers for SMA connectors? They conflict with LEDs... I can place them from inner side after cutting their edges, but on the outer side they will cover LEDs.

**Comment by jordens** [comment]
I don't insist. My conclusion is that the connector spacing is too small and that we need to go to 8 HP and a pattern similar to DIO_BNC. But I don't think we can do this in the resent revision.

**Comment by gkasprow** [comment]
@jordens going to 8HP involves adding vertical SMA connectors and additional PCB mounted vertically.
So let's leave it as it is.

**Comment by jordens** [comment]
@gkasprow or pigtails and panel mounted connectors. or even some non-standard mechanical design where the angled connectors are on both sides. ack, not something for now.

**Comment by gkasprow** [comment]
done.

**Comment by hartytp** [comment]
Thanks!

**Comment by hartytp** [comment]
@gkasprow If the boards have gone to manufacture, are all items at the top of this issue done? If so, can we close the issue?
