### ISSUE TITLE
Sayma RTM FPGA configuration

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#249]
The `M[2:0]` pins are wired `0b001`. That's [Master SPI](https://www.xilinx.com/support/documentation/user_guides/ug470_7Series_Config.pdf#page=51) mode. We would have to implement an entire slave SPI to support that configuration. And I don't think it works at all since `FCS_B` and `DIN` are not wired that way. Would be much better if we had `M[2:0] = 0b111` and [slave serial](https://www.xilinx.com/support/documentation/user_guides/ug470_7Series_Config.pdf#page=38).
Is that correct @gkasprow ?

**Comment by gkasprow** [comment]
@jordens you can have 0b111 - just get rid of R112 and short it with R116

![obraz](https://user-images.githubusercontent.com/4325054/29131290-ba83ed00-7d2c-11e7-8a7b-ddb22340fb8c.png)

**Comment by jordens** [comment]
@sbourdeauducq is the choice of slave serial as the configuration method correct?

**Comment by hartytp** [comment]
Moved to #216
