### ISSUE TITLE
3U BNC/SMA/RJ45 no glitches at power cycle

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#252]
3U SMA/BNC/RJ-45 outputs should be configured to high-impedance input at power-on

**Comment by gkasprow** [comment]
We can make them to be inputs with 10k to GND until they are switched to
desired mode by i2c command. This would ignore dip switch setting.

**Comment by hartytp** [comment]
Adding this to pre-existing 3U board errata issues.
