### ISSUE TITLE
SMA_IOx MOSFET connections are inverted

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#256]
The SMA_IO1_DIR MOSFET incorrectly controls the SMA_IO2 channel, and vice versa.

**Comment by hartytp** [comment]
Consolidating by moving this to Sayma AMC errata issue...

**Comment by sbourdeauducq** [comment]
Having a single "errata" issue is not a good idea: no history, content can be easily deleted with no possibility of recovery, potential conflicts if two people edit it at the same time.
Better create 1 issue per problem and use milestones.

**Comment by gkasprow** [comment]
This is correxted on boards you have

20.08.2017 07:48 "Sébastien Bourdeauducq" <notifications@github.com>
napisał(a):
