### ISSUE TITLE
DDS RSET

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#275]
* Take really good care placing and choosing DAC_RSET (R70 and R102) as those are stability relevant. Consider making the DDS current set resistors decent temp co (say, 25ppm/K) for improved amplitude stability (e.g. if this is ever used open-loop to drive quantum logic gates).

**Comment by gkasprow** [comment]
10K 0.1% 25ppm

**Comment by hartytp** [comment]
@gkasprow Let's not bother with the 25ppm/K resistor. Just put a standard resistor here.

General comment: I don't like putting low temp co components on the PCB unless we have a good reason to think they are doing good.

**Comment by dhslichter** [comment]
My suggestion here would be to ensure that the resistor footprint and location are such that users could resolder a new one with lower tempco if desired.  Basically 0402 minimum, prefer 0603 if there is space, and with reasonably accessible solder pads.
