### ISSUE TITLE
Urukul clock fanout

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#277]
* [x] AC-couple shield of CK_SMA_IN (J2). (@hartytp edit: IMO this is worth doing on the PCB, even if we decide not to isolate it on the first version of the front panel)
* [ ] Why do you feed the single ended DDS0_SYNC_CLK also to the negative input (1) of IC4?
* [x] Delete R45 and R81 and DNP C194, C81 in that variant. The negative inputs of IC17 are already taken care of.

**Comment by gkasprow** [comment]
@jordens IC4 is used as LVCMOS to LVDS converter. It has higher bandwidth and lower delay than standard converter ICs. We already discussed it.

**Comment by gkasprow** [comment]
@jordens THe idea is to feed the SYNC signal directly to the LVDS, without CPLD delay.
