### ISSUE TITLE
Urukul synchronization trace langth matching

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#278]
* We'd like the DDS_CLK from the clock distribution to be coincident at all DDS to significantly better than 100 ps.

* To get the DDS synchronization working, we need to ensure that (assuming DDS_CLK is matched):
  1. `DDS[3:0]_SYNC_IN`: The SYNC distribution needs to meed S/H w.r.t. the DDS clock, I.e. SYNC_IN needs to be coincident at the DDS to 100ps.
  2. `DDS_UPDATE[3:0]`: IO_UPDATE needs to meet S/H w.r.t. SYNC_CLK at the DDS, I.e. the IO_UPDATE lines after the CPLD need to be length matched to 100ps.
  3. For the AD9912 case, match the `DDS_RESET` lines after the CPLD to 100ps.

* Also we would like to have the DDS outputs coincident with the RF switching signals at the RF switches (to match envelope and signal). For that we need to (a) length match the DDS outputs to the baluns (assuming the paths are matched from the baluns to the RF switches) and (b) length match the path from the EEM connectors (`IO_B[12:15]`; i.e. the last four pairs on EEMB) to the CPLD (through and including the LVDS xceiver) as well as after the CPLD on `RFSW_CTRL[3:0]`. This will be limited by CPLD delay/routing variations. But let's try to be good on the layout.

**Comment by hartytp** [comment]
- [ ] Should DDS_SYNC_CLK0 be AC coupled to avoid current draw into biasing resistors?

**Comment by gkasprow** [comment]
@hartytp I can increase the bias resistor values. I used 220R since they were already in the design.

**Comment by jordens** [comment]
IIRC that is only a pretty weak output from the DDS.

But I think @hartytp is not so much referring to the bias resistor value and more to the possivble addition of an ac coupling to convert weak single ended 3.3V CMOS (?) to LVDS. There, I guess, are different options to achieve that. With AC (and zero common mode at the LVDS input) and with DC (and some common mode swing at the LVDS inputs) coupling...

**Comment by gkasprow** [comment]
Anyway, 1k load is really light and every CMOS can handle it.

**Comment by hartytp** [comment]
> Anyway, 1k load is really light and every CMOS can handle it.

Okay, feel free to leave it as is then.

**Comment by dhslichter** [comment]
I am not sure sure about that, check the IBIS models @gkasprow ...the SYNC pins are pretty pathetic on these DDS chips.

**Comment by jordens** [comment]
- [ ] You didn't match `DDS_RESET` AFAICT. The branch to the AD9910 does not need to be matched. But the one to the AD9912 does.
- [ ] ~For the RF switch action to be coincident with the DDS signal, the traces from the DDS (both) outputs to the baluns would need to be matched as well...~ But let's delay that for v1.1.

**Comment by gkasprow** [comment]
1cm of trace is roughly 50ps. CPLD skew is higher than that.
In case of Reset line I had to add passive source termination. Otherwise this would not have much sense.
I spit it to reset dedicated to 9912 and 9910

**Comment by jordens** [comment]
Please elaborate how you implemented this. The `DDS_RESET` (not `DDS_I/O_RESET`) needs to be **coincident at all AD9912** (the AD9910 don't matter). It isn't AFAICT. It comes in at the top and travels to the bottom. The 10cm board height would be 500ps skew between the top and bottom DDS.

**Comment by gkasprow** [comment]
@jordens Sure, I just fixed it.
I source-terminated all resets that go to 9912. Otherwise you will get ringing.
9910 reset is routed to another CPLD pin to not load 9912 reset pin.

**Comment by jordens** [comment]
Ok. That sounds good. I had interpreted your comment as something that you had already implemented.

**Comment by gkasprow** [comment]
@jordens can we produce it as it is? There will always be some issues and every board can be routed better.

**Comment by jordens** [comment]
Yes. Please go ahead. AFAICT you addressed all pertinent issues.

**Comment by hartytp** [comment]
Thanks for finishing this off Greg! Looking forward to the prototypes arriving.

**Comment by hartytp** [comment]
@jordens Can we close this?

**Comment by jordens** [comment]
From my view yes. Generally @gkasprow should close them as the one who fixes them. The syntax is [a bit more restrictive](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by gkasprow** [comment]
Well, I used syntax: fixed and then series of issues.

**Comment by jordens** [comment]
Correct. You need to repeat the keyword for each issue.
