### ISSUE TITLE
test JESD204B waveform demo gateware

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#28]
JESD204B waveform demo is complete. https://github.com/m-labs/artiq/issues/580. Here are some tests I will do. 

**phase noise**
- use Symmetricom 5125A
- DAC outputs sinusoid at 100 MHz, 250 MHz
- [x] measure phase noise between pair of DAC channels
- [ ] measure phase noise between REF and a DAC channel
- this is a duplicate of measurements made by Slichter this spring

**long-time operation**
- look for programming and bit errors
    - set 100 MHz frequency repeatedly in ARTIQ Python program (long loop), compute phase offset to maintain continuous phase
    - between RF and a DAC channel...
    - [ ] frequency wander: look for frequency drift over time  
    - [ ] glitch: look for missed oscillation over interval 1000 s using counter
    - glitch: program 50% duty cycle square wave 0V, 1V at 10 MHz
    - [ ] trigger scope at 1.2 V to look for bad data word

**absolute phase**
    - confirm phase stability relative to KC705; write ARTIQ Python program generating experiment start pulse, with parallel: set phase of two RF channels; schedule program repeatedly on Master; trigger scope on start pulse; measure jitter 
    - [ ] above for RF tone

- documentation & code 
  - [x] setup instructions 
  - [x] RTIO interface 
  - [x] interface with ARTIQ Python

**Comment by jbqubit** [comment]
Measure DAC0 to DAC1 phase noise. 

## Oscillators
OSC10a is free-running 10 MHz Wenzel (501-04609).
OSC100a is 100 MHz Wenzel (501-23588) locked to free-running 10 MHz Wenzel (501-04609). 
SYN2000a is ADF5355 PLL Eval Board is generating 2 GHz with OSC100a as reference 

## Measure
Measure DAC0 to DAC1 phase noise on AD9154 FMC Eval board using KC705 and Syn2000a. Use Symmetricom 5125A with two input ports (Ref and Input).  

![image](https://cloud.githubusercontent.com/assets/20543958/20157431/f5c12e98-a6a2-11e6-818d-8eef8764fac7.png)
(above, blue) Input: DAC CH0 100 MHz, Ref: DAC CH1 100 MHz
(above, pink) Input: DAC CH0 250 MHz, Ref: DAC CH1 250 MHz

![image](https://cloud.githubusercontent.com/assets/20543958/20157434/f9481964-a6a2-11e6-9990-3ca919ef16bf.png)
(above) AD9154 data sheet (for comparison)

The channel-to-channel phase noise is less than the external-clock to channel phase noise. This is as expected. 

TODO: 
- [ ] Measure channel-to-clock phase noise. This requires a 2 GHz source with low phase noise. I've got one on order.

**Comment by hartytp** [comment]
@jbqubit Has this been taken care of by the ARTIQ issues you've filed? Do we need to keep it open here?

**Comment by jbqubit** [comment]
I've tested most of these -- checkmarks updated. Closing.
