### ISSUE TITLE
Kasli EEM power specification

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#284]
* [x] What current are the IDCs/ribbon cables rated to?
* [x] What current can the copper plane and the barrel connector take?
* [x] Add a stated limit to the schematics.

**Comment by gkasprow** [comment]
@jordens Current rating is [here](https://multimedia.3m.com/mws/media/920107O/3m-tech-brief-current-rating-of-common-3mtm-flat-ribbon-cable.pdf). 1A per wire is standard value and we have 2 wires in parallel. IDC is also specified at 1A per pin.
Barrel connector is specified for 5A. 
In case of copper plane there is no limit - after power integrity simulation one iterates until current density is lower than let's say 50A/mm2.

**Comment by jordens** [comment]
Thanks. I updated the [wiki](https://github.com/m-labs/sinara/wiki/EEM#eem-idc-electrical-interface).
