### ISSUE TITLE
Kasli FTDI DDBUS

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#286]
If there is space, expose the last port (DDBUS) of the FTDI as a DNP 100 mil pin header row. If not, leave it.

**Comment by marmeladapk** [comment]
@jordens  Do you want to have all 8 pins exposed?

**Comment by jordens** [comment]
As many as you have space. But it does look really crowded already.

**Comment by marmeladapk** [comment]
Done in latest commit
