### ISSUE TITLE
Use Si53312 as clock fanout/mux/divider

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#295]
from #270 

  * DIVA shorted with DIVB connected to the CPLD

There are two wiring options here: 

- A:
  * All AD9912 to the A-bank,
  * All AD9910 to the B-bank,
  * terminate only the ones in use in that variant

- B
  * All AD9912 and AD9910 to the A-bank on top of each other
  * Leave the B-bank unused
  * terminate only the A-bank

A has the advantage of zero stubs on the clock lines but uses a bit more routing. B uses less routing, but has stubs (either on the clock pair or on the analog output).

**Comment by hartytp** [comment]
@jordens I'd definitely like a way of disabling the divider for the AD9910 e.g to allow a 1GHz clock input. So, even in option A, I'd still route DIVB to the CPLD.

**Comment by hartytp** [comment]
Other than that, I'd go for option A if we can route it without having to add additional layers.

**Comment by jordens** [comment]
Oh yes. I forgot about that.

**Comment by gkasprow** [comment]
option A implemented. closing.
