### ISSUE TITLE
Kasli VCCO

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#299]
Right now we have 2.5 V IO voltage.
Would it be wise or possible to move to 3.3 V IO voltage?
I know this is pretty late, but the change from 1.8 V to 2.5 V just happened.

* We'd save a bunch of 2.5 <--> 3.3 level translators.
* It would free up one power supply rail, making room for VCCAUX/VCC_XDAC (#297)
* LVDS is not affected AFAICT.
* Maybe a bit higher power consumption.

**Comment by marmeladapk** [comment]
> The "LVDS_33" I/O Standard that was available in some older FPGA
families, is not supported in 7 series.
> Neither High Range (HR) banks, nor High Performance (HP) banks can have
their VCCO pins powered at 3.3V (if using LVDS outputs).

[Source](https://www.xilinx.com/support/answers/43989.html)

**Comment by jordens** [comment]
Ah. Never mind then.
