### ISSUE TITLE
kintex ultrascale support

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#3]
m-labs/artiq#563

**Comment by hartytp** [comment]
@jordens Do we need to keep this issue open? Isn't the ARTIQ issue enough?

**Comment by jordens** [comment]
Ack. Gateware and firmware can be tracked in artiq.

**Comment by hartytp** [comment]
Thanks. Same goes for: #2 #6 #28 and #139.

**Comment by jordens** [comment]
I don't know about Joe's issues. But 2 and 6 should remain open until they are migrated.

**Comment by hartytp** [comment]
Okay. @jbqubit can we move #28 and #139 to ARTIQ (or close them)? It seems more sensible to keep this repo for hardware and use ARTIQ to track gateware issues.

**Comment by jbqubit** [comment]
I closed #28 and commented on #139.
