### ISSUE TITLE
AC coupling on CLK_CDR_IN

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#303]
CLK_CDR_IN clock input is not AC coupled - R9 and R13 make DC loop

**Comment by jordens** [comment]
On the other hand, CKIN2+- are probably internally biased (I couldn't tell from the datasheets but they are only used AC coupled). You can't short that with R13. That one should be DNP. And without the balun, there should be a 0R to GND in front of C14.

**Comment by marmeladapk** [comment]
@jordens You're right, though [this document](https://www.silabs.com/documents/public/reference-manuals/si53xx-reference-manual.pdf#G1251443) mentions: 

> AC coupling the input clocks is recommended because it removes any issue with common mode input voltages. However, either ac or dc coupling is acceptable.

I'll add capacitor before balun for sma and mmcx connectors.

**Comment by jordens** [comment]
But the implied statement is that you have to obey the common mode voltage i.e. the biasing.

**Comment by marmeladapk** [comment]
That's absolutely right.
