### ISSUE TITLE
Kasli clock input annotations

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#306]
- [x] Add a brief annotation for the solder jumpers on the SMA clock input for Kasli. Annotation should say something like "For clock input ("master" mode), populate ..., for clock output ("slave" mode) populate ..."

**Comment by jordens** [comment]
"DRTIO master" and slave are well defined.
All correct. Just that in master mode Kasli gets the clean clock over that connector. The jitter attenuation effect is not important in that case. In slave mode Kasli recovers the clock from the serial link to the upstream DRTIO master and that needs cleaning. And it is convenient to then output that clock on the connector for other purposes.

**Comment by marmeladapk** [comment]
Please check if current note is verbose enough.

**Comment by hartytp** [comment]
Current annotation looks good to me. Thanks!

**Comment by hartytp** [comment]
Current annotation looks good to me. Thanks!
