### ISSUE TITLE
connect AD9910 EXT_PWR_DWN to GND

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#308]
Datasheet says "If unused, connect to ground."

**Comment by gkasprow** [comment]
@jordens It also says that has pulldowns, but OK, I will connect to GND.

**Comment by dhslichter** [comment]
I recommend a solder jumper here; this would allow users who don't need all 4 DDS's to power down some channels to reduce power consumption/heat load.

**Comment by jordens** [comment]
@dhslichter that's more convenient to do in software.

**Comment by dhslichter** [comment]
@jordens ack, works for me.
