### ISSUE TITLE
Kasli schematic clean up

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#311]
- [x] I find the annotation "Replace 0R with 100k for AC coupling" a bit misleading -- to me "AC coupling" implies AC coupling of a signal, rather than the ground. IMO something like "Replace 0R with 100k to isolate grounds." (or at least "to AC couple grounds.") would be better. If there is room, it might be worth adding "Replace 0R with 100k **and fit insulating washer on SMA** to isolate grounds." (but that's getting a little verbose!). This affects both the annotation at the SMA and at the MMCX connector.

- [x] Current consumption for the ADCLK948/ADCLK944 in the power budget table looks wrong -  shouldn't it be lower because not all outputs are used, and not all negative outputs are biased?

- [x] Rename "CLK_SMA_IN" (it's no longer an SMA). Better might be CLK_EEM_EXT or something like that. For consistency/clarity, it might also be worth renaming BUF_IN to something like CLK_EEM_INT.

- [x] Similarly, CLK_CDR_IN is not a good name, since this clock will often come straight from an XO or similar. I'd go for simply CLK_IN. For consistency, I'd also rename CLK_CDR_OUT to just CLK_OUT.

- [x] Why is there still an "ADD LEDS" annotation on the front page? Can that be removed now?

**Comment by hartytp** [comment]
Other than this and the issues raised in #296, I'm happy to sign off on the schematics (although, I haven't looked in detail at the FPGA, RAM, etc).

**Comment by marmeladapk** [comment]
> Current consumption for the ADCLK948/ADCLK944 in the power budget table looks wrong - shouldn't it be lower because not all outputs are used, and not all negative outputs are biased?

I made maximum, worst case power budget (for example when user populates DNP resistors). I'll change values for ADCLK944, since one output is not connected.

**Comment by hartytp** [comment]
> I made maximum, worst case power budget (for example when user populates DNP resistors). I'll change values for ADCLK944, since one output is not connected.

Okay, that makes sense. Thanks!

**Comment by hartytp** [comment]
Thanks for fixing that so quickly!
