### ISSUE TITLE
Kasli power supply decoupling

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#316]
[Xilinx UG483](https://www.xilinx.com/support/documentation/user_guides/ug483_7Series_PCB.pdf#page=16) mentiones that you need a bunch of decoupling caps for our FPGA (XA7A100T-FGG484). I can't find that in current schematics (e.g. any of the 330 µF, 100 µF, 470 µF caps and many of the smaller ones). Could you verify the size, quantity and ESL/ESR? Maybe this was forgotten in the change to the larger size.

**Comment by jordens** [comment]
* VCCAUX should get 3x 4.7 µF
* MGTAVCC should have 1x 4.7 µF
* MGTAVTT should have 1x 4.7 µF

I am not too spooked about those since there are a bunch of 22 µF close by. Just to confirm that you chose to deviate from the datasheet deliberately.

And as mentioned elsewhere C91 is unlikely to survive on the bottom.

For the next revision we should consider either splitting all 47 µF into 22 µF or merging/upgrading all 22 µF to 47 µF to save a BOM line.

**Comment by marmeladapk** [comment]
Each one of those is missing one 4,7 uF and has 22 uF nearby, it was intentional.
