### ISSUE TITLE
Urukul heat sink

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#325]
Back side
Exposed copper
See note in #291

**Comment by dhslichter** [comment]
Solder mount?

**Comment by gkasprow** [comment]
There are tiny copper heatsinks that can be placed by P&P machine and  reflow soldered. I will leave bottom part of thermal pad exposed. Anyway, one should not cover vias from one side because it creates pockets so would leave them open anyway.
So when needed, we can easily solder such heatsink.

**Comment by dhslichter** [comment]
Are you not planning to use epoxy-filled vias under the DDS chips?  From what I understand, assembly and exposed paddle solder joint quality are considerably better if the vias are filled, rather than empty or soldermask-tented.

**Comment by gkasprow** [comment]
We will use soldering paste on both sides and let it flow in and fill  vias entirely, It has much better characteristics than epoxy. Guys who do assembly know how to control the process to have the vias filled with tin..

**Comment by gkasprow** [comment]
I added enlarged, exposed pad on bottom layer, covered with solder paste. This should effectively increase heat dissipation area. In case of troubles, we will solder copper pads that would further increase the area.
