### ISSUE TITLE
Kasli: put a 125 MHz clock to MGTREFCLK1

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#331]
For Ethernet (125 MHz) and DRTIO (100, 125, 150 MHz) on the same quad we need more clocking flexibility. Sorry for noticing late.

* [x] You could e.g. take the KC705 setup with a 25 MHz XTAL and a clock gen or if you have something smaller/simpler, anything else that you have experience with. 
![screenshot from 2017-10-11 11-00-28](https://user-images.githubusercontent.com/1338946/31431268-72970482-ae73-11e7-80b9-aca504da73a3.png).
  Or maybe just [CCLD-033-50-125.000](http://www.crystek.com/crystal/spec-sheets/clock/CCLD-033.pdf) or [Si531](https://www.silabs.com/documents/public/data-sheets/si530.pdf) used in the RTM-SATA adapter.
* To make up some space for the crystal, completely remove:
  * [ ] the wire bridge W1[ABC], and
  * [ ] the SI5324 LOL circuitry (R15, LD1, T1), and
  * [ ] IC5 plus its periphery.
  * [ ] And on second thought, I just realized how large J24 is. Just drop it. I don't think we will be able to make use of it.
  * [ ] And finally you can remove OSC1 (plus periphery). If we get 125 MHz always on MGTREFCLK1, then we can just export that to the fabric via `IBUFDS_GTE2`.

**Comment by jordens** [comment]
@marmeladapk @gkasprow ping. How is the routing going? If we need to simplify this by e.g. reducing the EEM connector number, we should discuss this it now.

**Comment by marmeladapk** [comment]
@jordens Space is not really a problem and removing anything from your list is not necessary unless you feel something is redundant and won't ever be used. I'm fine with leaving everything as is and adding 125 MHz clock source (you want it on MGTREFCLK1, right?).

**Comment by jordens** [comment]
@marmeladapk yes. On the currently unused mgtrefclk input. The list of items to remove is just there to speed up and simplify the layout job. If you say removing them does not help with that, then feel free to keep them ;) you are the expert.

**Comment by marmeladapk** [comment]
I added [510FBA125M000AAG](https://www.silabs.com/documents/public/data-sheets/si510-11.pdf) Are you fine with it?

**Comment by jordens** [comment]
Sure. That's fine. I don't know whether it makes sense to harmonize that one oscillator with the one from the RTM-SATA adapter.

**Comment by jordens** [comment]
Oops. Wrong button. Feel free to close this when you think this is resolved.

**Comment by hartytp** [comment]
@marmeladapk what's the status of Kasli? When will it be ready for manufacture?

**Comment by marmeladapk** [comment]
Should be this week.

**Comment by marmeladapk** [comment]
@hartytp After consultation with Greg it'll be ready on Monday.

**Comment by hartytp** [comment]
Great!

**Comment by gkasprow** [comment]
At the moment there are just cosmetic things to fix - polygons, additional vias, copper balancing.
PI simulations look good.

**Comment by hartytp** [comment]
How did the thermal sim look?

**Comment by gkasprow** [comment]
Not done yet.
