### ISSUE TITLE
Pins confusion on 3U_VHDCI_Baseboard schematic

### ISSUE THREAD

**Issue by mntng** [m-labs/sinara#338]
LVDS2_1 in J41 and LVDS2_1 in J44A  are not connected on the board. LVDS1_2 in J44A is connecting to LVDS2_1 in J41 instead.

**Comment by jordens** [comment]
rev1.0 or rev1.1?

**Comment by gkasprow** [comment]
@mntng we changed clock routing between rev 1.0 and rev 1.1

**Comment by gkasprow** [comment]
Oh, @jbqubit  has one piece of very first VHDCI prototype. I forgotten about it!

**Comment by mntng** [comment]
rev1.0

**Comment by gkasprow** [comment]
OK, so pin definition is slightly different
[PCB_VHDCI_breakout rev1.pdf](https://github.com/m-labs/sinara/files/1402363/PCB_VHDCI_breakout.rev1.pdf)
