### ISSUE TITLE
Urukul Panel

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#340]
@jordens How do you want to have LEDs marked on the panel?
![obraz](https://user-images.githubusercontent.com/4325054/31866229-cbc84b94-b77c-11e7-8b53-6bc776d0aed2.png)

**Comment by jordens** [comment]
No Labels for the LEDs (other than pwr and temp). put the v1.0 on there. Use the same location for the logo, the board name, description, and version as for the other boards like the sma dio. Otherwise very good!

**Comment by gkasprow** [comment]
@jordens location for name and logo is same.

**Comment by gkasprow** [comment]
[Here](https://github.com/m-labs/sinara/tree/master/ARTIQ_ALTIUM/PANELS/Project%20Outputs%20for%20PANELS) are producction files

**Comment by hartytp** [comment]
Looks really nice @gkasprow!

When are the prototypes due in?

**Comment by gkasprow** [comment]
@hartytp I expect them within 2 weeks.

**Comment by hartytp** [comment]
:)
