### ISSUE TITLE
Urukul pinouts

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#341]
In light of #328 , @gkasprow , could you 

- [x] point out the exact commit that the manufacturing data is based on, and
- [x] ould you give me the final PDFs and 
- [x] CPLD pinouts so that we can start writing the CPLD code?

**Comment by gkasprow** [comment]
It is tagged production_v1
pdf are [here](https://github.com/m-labs/sinara/tree/master/ARTIQ_ALTIUM/Kasli/3U/PCB_3U_DDS/Project%20Outputs%20for%20PCB_3U_DDS)
CPLD pinout is [here](https://github.com/m-labs/sinara/blob/master/ARTIQ_ALTIUM/Kasli/3U/PCB_3U_DDS/CPLD_code/CPLD_pinout.xlsx)

**Comment by jordens** [comment]
@gkasprow 
* You added three tags to commit f8354065 
* I removed all of them because that commit is from May.
* Which commit corresponds to the altium files that the production was based on?

**Comment by jordens** [comment]
Is f2c83b2 correct?

**Comment by gkasprow** [comment]
I added by chance, then removed but it failed to sync after that.
Yes f2c83b29697ec44a3b97be62d8c359dcdbd4cefd is production version

**Comment by jordens** [comment]
* I created https://github.com/m-labs/sinara/releases/tag/Urukul%2Fv1.0 at that commit
* and uploaded the PDFs and pinout xls to that release.
* Could you upload Gerbers, XY and BOM (preferrably all in a zip or tar.gz file) to https://github.com/m-labs/sinara/releases/edit/Urukul%2Fv1.0

**Comment by gkasprow** [comment]
done

**Comment by jordens** [comment]
@gkasprow could you please clean up https://github.com/m-labs/sinara/releases?
Delete your tags, also from your working tree and from @marmeladapk
