### ISSUE TITLE
Urukul CPLD code for testing

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#344]
@gkasprow how do plan to test Urukul, the DDS, and the attenuators? Does the code I wrote to implement the current Urukul design specification work for you (https://github.com/m-labs/urukul)? Are you going to roll your own testing code that just connects one DDS at a time so you can use the ADI eval board?

(from #292)

**Comment by gkasprow** [comment]
@jordens I planned to use ADI tools + usb->SPI converter to talk to attenuators in a way I did with Novo board. CPLD is another story, I will try to use your code.

**Comment by jordens** [comment]
Does the converter work with an CS configuration that is not "one-hot" but a chip address?

**Comment by gkasprow** [comment]
I can generate any state because it is based on FPGA with FORTH processor.

**Comment by jordens** [comment]
Ok.

**Comment by gkasprow** [comment]
@jordens could you please briefly describe functionality of the code you wrote? I'd like to just burn FLASH and start testing without analysing it.

**Comment by gkasprow** [comment]
I've just noticed that Python code is self-explanatory :)

**Comment by jordens** [comment]
Yes. Should be well documented. If you hit issues, please file them over there.

**Comment by gkasprow** [comment]
@jordens could you build this code? I just need binary file.

**Comment by jordens** [comment]
It's all in the releases.

**Comment by jordens** [comment]
And please also file questions like that one over there.

**Comment by gkasprow** [comment]
@jordens I don't see CPLD binaries in releases...

**Comment by jordens** [comment]
There are .jed, .isc and .vm6 files. Those are the "binaries".

**Comment by gkasprow** [comment]
@jordens I don't see them. Point me please.

**Comment by jordens** [comment]
* https://github.com/quartiq/urukul -> release -> v1.0rc5 ->
* https://github.com/quartiq/urukul/releases/download/v1.0rc5/urukul_v1.0rc5.tar.gz

**Comment by gkasprow** [comment]
thanks, I looked at wrong file then.
