### ISSUE TITLE
Kasli v1.1 cost savings

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#347]
# Do not act on this now. Wait for v1.1.

* [ ] consider either splitting all 47 µF into 22 µF or merging/upgrading all 22 µF to 47 µF to save a BOM line
* [x] ~make OSC1 125 MHz as well (same BOM as OSC2) or drop it~ (moved to errata)
* [ ] determine cost contribution of likely unused parts: MMCX connectors, make them optional BOM items.

**Comment by marmeladapk** [comment]
- [ ] Improve signal integrity for backplane LVDS lines (remove reference plane cut)

**Comment by hartytp** [comment]
> determine cost contribution of likely unused parts: MMCX connectors, clock fanouts, make them optional BOM items.

FWIW, unless there is a noise issue with this clock source, we will definitely make use of these connectors for our DDS clocks. I imagine that other groups using the DDS will as well.

While I think the aim of trying to reduce cost/complexity/power is laudable, @gkasprow has already commented that the MMCX connectors cost $1 each, so IMO the extra time/cost/hassle associated with maintaining different population options far outweighs the cost savings from removing these components.

NB the clock fanout is also required as a mux to select the clock source fed to the backplane, so removing it will cause additional problems.

**Comment by jordens** [comment]
I'd like to know how much the composition of the cost per board and how much these actually contribute to the price. From the board house.
AFAIK you would also be happy with only 4 instead of 7 mmcx.

**Comment by hartytp** [comment]
> AFAIK you would also be happy with only 4 instead of 7 mmcx

Sure, 4+ is fine IMO if you want to save a few $

**Comment by hartytp** [comment]
Are there any cost savings we want to make to Kasli?

AFAICT, there are no easy places to save money on the design (but correct me if I'm wrong about that @gkasprow @marmeladapk) so I'm closing this.
