### ISSUE TITLE
Urukul v1.0 errata

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#348]
- [ ] Subsignals like IOA_n should be renamed to something like EEM0_n or IO0_n since we renamed the EEMs from EEMA/EEMB to EEM0/EEM1.
- [ ] Use a currently unused CPLD pin for DDS select: pulled high by a 0R resistor if AD9910 populated, pulled low if AD9912 populated. (In the current version, we have to use the dip switch, which is less convenient for the users).
- [ ] R52 and R47 are still wrongly DNP in the AD9912 variant
- [ ] place ARTIQ/Sinara logos on the PCB
- [ ] Silk + schematic + panel should be "v1.x" not "rev1.x"

**Comment by jordens** [comment]
moved to #377 (should be the other way around, but there is inertia)
