### ISSUE TITLE
Clocker v1.0 testing

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#355]
- [ ] Check output square waves look clean -- no excessive ringing or signs of internal reflections. Reflections etc can decrease the effective slope of the signal near the zero-crossing and significantly degrade phase noise performance.
- [ ] Input return loss
- [ ] Edge rise/fall time (NB this needs a very fast scope, not worth doing if the scope isn't as fast as the ADCLK948!)
- [ ] Phase noise/amplitude noise
- [ ] Output power versus frequency up to > 4GHz

Use 100MHz reference frequency (very low noise source, such as Wenzel oscillator) for all tests, input should be ~+10dBm.

**Comment by hartytp** [comment]
@gkasprow My suggestion is that you do basic functionality/no-smoke testing and then ship the boards to us for detailed testing. @WeiDaZhang can you perform the tests above once the boards arrive, please? (If you like, you can also look at the phase stability, but that's not crucial IMO).

**Comment by gkasprow** [comment]
@hartytp OK, this board was meant as a quick design job, with no intensive testing.

**Comment by hartytp** [comment]
> @hartytp OK, this board was meant as a quick design job, with no intensive testing.

Yes. We'll take care of any testing that needs to be done.
