### ISSUE TITLE
Kasli FPGA release data

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#356]
@marmeladapk Could you tag the commit corresponding to the Kasli v1.0 production data with "Kasli/v1.0", create a release, and upload PDFs, Gerbers, BOM, XY, and the FPGA pinout to the release?

**Comment by gkasprow** [comment]
Hold on until we get confirmation from PCB worksop that there are no changes required.

**Comment by marmeladapk** [comment]
As Greg said, I was planning to do that after final changes required by the manufacturer (that's why I pushed rc version).

**Comment by jordens** [comment]
ACK. Sounds good.

**Comment by jordens** [comment]
@marmeladapk : according to @gkasprow Kasli is in production. could you please upload the release data so we can start preparing?

**Comment by jordens** [comment]
Especially the FPGA pinout

**Comment by marmeladapk** [comment]
Done.

**Comment by jordens** [comment]
Well done. Thanks!
