### ISSUE TITLE
RF PA design files

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#359]
@thomasRF @gkasprow I'm interested in having a look at the RF PA design in microwave office. Do you already have a microwave office model of it? If not, I'm happy to build one, but can you confirm that the schematics [here](https://github.com/m-labs/sinara/tree/master/ARTIQ_ALTIUM/PA_8CH/PA_Channel/PA_Channel_RF) are up to date?

**Comment by gkasprow** [comment]
Tomasz has MO model.
