### ISSUE TITLE
Kasli thermal simulations

### ISSUE THREAD

**Issue by marmeladapk** [m-labs/sinara#360]
I did some thermal simulations of Kasli board.
Environment (same as in Urukul tests, only board orientation is different):
<img width="377" alt="env" src="https://user-images.githubusercontent.com/24512604/32808324-ef2140d2-c992-11e7-8d33-9a9d1c2ac868.png">
No cooling:
<img width="638" alt="thermal-no-cooling" src="https://user-images.githubusercontent.com/24512604/32808343-0378214a-c993-11e7-9503-40367ad38c6e.png">
50 cm/s airflow:
<img width="638" alt="thermal-50cm-s" src="https://user-images.githubusercontent.com/24512604/32808359-0f4ec7f8-c993-11e7-9850-bb5b6b527b02.png">
130 cm/s airflow:
<img width="555" alt="thermal-130cm-s" src="https://user-images.githubusercontent.com/24512604/32808368-16d8c604-c993-11e7-93e5-a014e0451e1f.png">

**Comment by hartytp** [comment]
cf #321

**Comment by hartytp** [comment]
So, max temperature for Kasli looks pretty similar to Urukul for a given air flow...

**Comment by gkasprow** [comment]
This is worst case scenario with all power rails fully loaded.

**Comment by jordens** [comment]
Lgtm

**Comment by marmeladapk** [comment]
Do you want to see power supply simulations I did while optimising the board?

**Comment by jordens** [comment]
Sure! This is all very valuable information. I'd guess also for your thesis.

**Comment by marmeladapk** [comment]
P1V0:
<img width="952" alt="p1v0_current" src="https://user-images.githubusercontent.com/24512604/33656393-3b3e5dda-da76-11e7-910e-5a87bfb5e493.png">
<img width="952" alt="p1v0_drop" src="https://user-images.githubusercontent.com/24512604/33656394-3b5b34fa-da76-11e7-80f8-ec3d87626fbc.png">

P1V2:
<img width="952" alt="p1v2_current" src="https://user-images.githubusercontent.com/24512604/33656395-3b7445e4-da76-11e7-881d-089f81bceb70.png">
<img width="952" alt="p1v2_drop" src="https://user-images.githubusercontent.com/24512604/33656396-3b8f8782-da76-11e7-9e65-ba734d7d58d5.png">

P1V5:
<img width="952" alt="p1v5_current" src="https://user-images.githubusercontent.com/24512604/33656397-3bb3988e-da76-11e7-8799-5d0bf5d0eaf4.png">
<img width="952" alt="p1v5_drop" src="https://user-images.githubusercontent.com/24512604/33656398-3bd0d6ce-da76-11e7-96b7-64ca0ede36d6.png">

P1V8:
<img width="952" alt="p1v8_current" src="https://user-images.githubusercontent.com/24512604/33656399-3bf344e8-da76-11e7-8f0e-fceca9a2e839.png">
<img width="952" alt="p1v8_drop" src="https://user-images.githubusercontent.com/24512604/33656400-3c109d18-da76-11e7-84a1-4659e4e05118.png">

P2V5:
<img width="952" alt="p2v5_current" src="https://user-images.githubusercontent.com/24512604/33656402-3c50120e-da76-11e7-9494-c8d1a439076f.png">
<img width="952" alt="p2v5_drop" src="https://user-images.githubusercontent.com/24512604/33656403-3c7d18a8-da76-11e7-9208-b82d05585452.png">

P3V3:
<img width="952" alt="p3v3_current1" src="https://user-images.githubusercontent.com/24512604/33656404-3c95ba34-da76-11e7-99f9-fa6b04d3fe00.png">
<img width="952" alt="p3v3_current2" src="https://user-images.githubusercontent.com/24512604/33656405-3cb10208-da76-11e7-873b-c8dfda7e6667.png">
<img width="952" alt="p3v3_drop" src="https://user-images.githubusercontent.com/24512604/33656406-3cc93634-da76-11e7-8fbf-2e9ed75f17f6.png">

P12V0:
<img width="952" alt="p12v0_current" src="https://user-images.githubusercontent.com/24512604/33656407-3d0f6884-da76-11e7-9f22-44764a83a3ec.png">
<img width="952" alt="p12v0_drop" src="https://user-images.githubusercontent.com/24512604/33656408-3d316bd2-da76-11e7-9acd-005e863275a6.png">
