### ISSUE TITLE
Sayma_AMC shipped without uTCA mating connector

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#365]
@gkasprow Is the omission of the female uTCA AMC mating connector a design choice or inadvertent? 

![image](https://user-images.githubusercontent.com/20543958/32899403-e458c162-cab8-11e7-9e41-764389c64ad9.png)

**Comment by gkasprow** [comment]
@jbqubit Digikey has problem with their stock - they ship wrong version of the connector. There was batch of  purchased ones and it was returned. So we will ship missing connectors once they arrive.

**Comment by jbqubit** [comment]
Good call shipping boards without that connector as the boards seem to mate fine on the benchtop without it. Looks easy to solder-on down the line.

**Comment by gkasprow** [comment]
This connector is mounted with one screw only. No soldering required.

**Comment by jbqubit** [comment]
OK. Let's leave this open until the correct part arrives and is confirmed to work.

**Comment by jbqubit** [comment]
@gkasprow Did these come in yet?

**Comment by gkasprow** [comment]
I'll ask and let you know.

**Comment by jbqubit** [comment]
@gkasprow Any word on this?

**Comment by gkasprow** [comment]
We finally receive them all.
So together with other boards will ship them.
How many do you need?

**Comment by jbqubit** [comment]
I need qty 2. But Issue is also about confirming that once they're installed on the AMC that AMC and RTM mate correctly in the uTCA crate.

**Comment by gkasprow** [comment]
I will get them on Monday so will confirm it.

**Comment by hartytp** [comment]
@gkasprow Did you have a chance to check that these connectors fit yet? Once you've shipped the connectors, please can you close this issue?

**Comment by gkasprow** [comment]
yes, they fit perfectly. I shipped a few to Sebastien.

**Comment by hartytp** [comment]
@gkasprow to confirm I am still missing one if these.
