### ISSUE TITLE
Allaki insertion-removal, SMA connectors

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#366]
Using Sayma_RTM v1.0 and Allaki v0.1 there are some geometric difficulties that make insertion and removal of Allaki boards difficult. These don't appear to interfere with testing but need to be addressed before production. 

- Tolerances permit zero gap between Sayma_RTM and Allaki SMA. 
![image](https://user-images.githubusercontent.com/20543958/32900561-bcbff24e-cabb-11e7-8a9e-957c16fde361.png)

- Removal of Allaki is possible but requires lots of wiggling. This appears due to three points of binding per Allaki (x4) and RTM. (1) between RTM and tall SMA (2) SMA edge-connector smooth barrel and edge of RTM rear-panel (3) threaded SMA barrel catching on apertures in RTM rear-panel (not visible in photo). 
![image](https://user-images.githubusercontent.com/20543958/32900892-870c3008-cabc-11e7-9050-71c5698170b4.png)

**Comment by gkasprow** [comment]
@jbqubit this was already spotted by @jordens

**Comment by jbqubit** [comment]
I've found that prying the stainless frame upward slightly makes insertion/removal much easier... Is there a straightforward fix for this? Is it easier with the insulating face place?

**Comment by hartytp** [comment]
Closing this issue, as these problems should be fixed by changing the connectors on Allaki to SMPs and changing the way we do the front panels on Sayma.
