### ISSUE TITLE
AD9656 input configuration

### ISSUE THREAD

**Issue by dhslichter** [m-labs/sinara#38]
- [ ] 1. Use Schottky diodes for input protection on AD9656.  For each input, want diodes both to ground and +1.8V supply rail.  Diodes should be placed immediately next to AD9656, between AD9656 and filter/impedance matching component footprints.  Suggest [HSMS-286C-TR1G](http://www.digikey.com/product-detail/en/broadcom-limited/HSMS-286C-TR1G/516-1822-1-ND/1966528), which has low forward voltage and tolerates up to 4V reverse bias.  Series connected diodes, series anode to ground, cathode to +1.8 V rail.
- [ ] 2. Include 0603 pads for impedance matching/band defining components TBD.  Input impedace information for AD9656 available [here](http://www.analog.com/en/products/analog-to-digital-converters/ad-converters/ad9656.html#product-tools) in Excel spreadsheet form to enable component choices.  See also [AN-742](http://www.analog.com/media/en/technical-documentation/application-notes/587173998057911564087081655730496713845335290374441083AN_742_a.pdf?doc=AD9656.pdf) and [AN-827](http://www.analog.com/media/en/technical-documentation/application-notes/577685821057469457705578853404381574892535191189340957AN_827_0.pdf?doc=AD9656.pdf).  Connections should be differential only, no connections to ground or positive rail.  See drawing below.
  ![image](https://cloud.githubusercontent.com/assets/9222487/19819205/d9044830-9d10-11e6-8705-3f831a8be493.png)

**Comment by jordens** [comment]
What about ESD protection (i.e. some nice TVS)? Do we leave that to the mezzanine?

**Comment by hartytp** [comment]
I'd leave that to the mezzanine -- there are going to be relatively few cases where the input signal is coupled directly into the ADC, so protection will be needed upstream...

**Comment by jordens** [comment]
@hartytp ack
@dhslichter the lower diode needs flipping...

**Comment by dhslichter** [comment]
TVS is a disaster from a distortion standpoint, so we leave that decision to the mezzanine designers.  @jordens good catch on diode directions, have updated top comment to fix.

**Comment by dhslichter** [comment]
Further information on TVS vs Schottky for ADC input protection: http://www.analog.com/media/en/analog-dialogue/volume-49/number-2/articles/rf-samp-adc-input-protection.pdf

**Comment by dhslichter** [comment]
@sbouhabib please add any comments/thoughts here.
