### ISSUE TITLE
Sayma_AMC: PB3 SW (front panel button)

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#380]
The PB3 SW is routed to the MMC (LPC1776). Currently @gkasprow reports that it does nothing. What should its default behavior be? @sbourdeauducq 
1) MMC: reset, reconfigure from flash
2) AMC FPGA: reset, reconfigure from flash
3) RTM FPGA: reset, reconfigure from AMC FPGA

**Comment by sbourdeauducq** [comment]
Can't really see why we'd need a button there... maybe route to FPGA somehow and let users access it in ARTIQ kernels.

**Comment by gkasprow** [comment]
Well, I placed it for historical reasons - accelerator guys wanted to have one. We can always not mount it or remove in rev2

**Comment by jbqubit** [comment]
I'd like to use it for resetting the board -- something like outlined above. Seems like I use the reset button on the KC705 a couple times a day while debugging things. Its helpful to have this option without needing to attach a USB cable to the front. 

Longer term it would be nice if....
- short-press reload user-supplied .bit files
- medium-press load .bit files from DRTIO
- long-press reload golden-master configuration files -- for MMC, power chips, FPGAs

**Comment by marmeladapk** [comment]
@jbqubit Should this remain in milestone? @gkasprow does it require modifications to the AMC?

**Comment by gkasprow** [comment]
no, just implementation in MMC

**Comment by jbqubit** [comment]
I'd like to leave the button on the layout and connected to the MMC. Let's make the default behavior fully resetting Sayma. AFAICT this would consist of the following steps.
- soft power off of AMC+RTM LDOs
- reset MMC
- reconfigure MMC from flash
- trigger power-on of AMC+RTM LDOs
