### ISSUE TITLE
Sayma_AMC: MMC functionality

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#381]
What does the MMC currently do? @gkasprow Please respond with a list saying what it currently does.

What should it do? 
- PB3 SW (front panel button) #380 
- check for error messages from Exar power chips
- flash Exar power chips (MMC receives power even when Exar chips are not operational)

**Comment by hartytp** [comment]
@jbqubit Is this a documentation issue? Should it be reassigned to @filipswit and moved to the documentation milestone?
