### ISSUE TITLE
Sayma MMC steps during booting

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#429]
What are configuration steps done by MMC? List them one by one.

**Comment by gkasprow** [comment]
MMC performs following steps:
- configures CPU, UART
- sets port directions
- enables VCCINT PSU
- enables P5V0 PSU (helper PSU)
- enables Exar PSU. It boots from its own EEPROM
- waits 200ms
- configures SCANSTA chip in stitcher mode. If RTM is inserted, it enables its JTAG port
- configures I2C switch base address
- initializes default RTM power state to off
- initializes Ethernet PHY chip in RGMII mode using pin strap.
- waits 200ms
- initializes I2C controller and chain (switch)
- configures Si5324
- checks if RTM is inserted, if yes, then enables its power, waits 200ms and initializes RTM power supply via I2C. It also configures Si5324 on RTM
- runs task.

The task performs following functions:
- blinks front panel LEDs alternately
- checks if FPGA is configured. If not, it keeps Ethernet PHY in reset state
- checks if RTM is unplugged. If not, it switches the power off to make sure it is off during hotplug.
