### ISSUE TITLE
Sayma MMC serial interface

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#441]
The Sayma_AMC FTDI chip exposes four serial ports. 
- /dev/ttyUSB1
- /dev/ttyUSB2 :: usually the MiSoC console 
- /dev/ttyUSB3
- /dev/ttyUSB4 

Is the MMC [serial interface](https://github.com/m-labs/sinara/wiki/Sayma#mcc) mapped to one of these? I don't see any characters on the other serial ports.

**Comment by jbqubit** [comment]
Looks like it should be the 4th's USB interface from the schematic.

**Comment by gkasprow** [comment]
Yes, it is. Baud rate is 115200, 8, n, 1
You should get a message:
```
[00]Started. CPU clock = 80 MHz, SDRAM clock = 40 Mhz
LWIP HTTP Web Server FreeRTOS Demo...
Waiting for TCPIP thread to initialize...
Starting LWIP HTTP server...
Net up
PHY init done
```

**Comment by jbqubit** [comment]
And, pressing the front panel button should trigger issuance of additional debug info, right? 

I don't see that on any of the four serial ports....

**Comment by gkasprow** [comment]
@jbqubit  I added this feature recently when was debugging Ethernet PHY.
I will add Exar support and ask you to do firmware upgrade.

**Comment by jbqubit** [comment]
OK. Please work with @filipswit to document how to flash MMC independent of ARTIQ. https://github.com/m-labs/sinara/issues/428 Let me know when the updated firmware is ready.

**Comment by hartytp** [comment]
@jbqubit Can we close this issue now?

AFAICT the documentation component of this is taken care of in a separate issue, and the firmware upgrade is being tracked more accurately in the 1V8 supply issue.

**Comment by jbqubit** [comment]
> firmware upgrade is being tracked more accurately in the 1V8 supply issue.

This is an atomic feature that can be delivered and tested independent of the Exar debug info. Let's leave it open.
