### ISSUE TITLE
Kasli tests & errata

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#442]
@jordens The Kasli arrived.
![2017-12-15 14 41 27](https://user-images.githubusercontent.com/4325054/34045595-e0f82e24-e1a9-11e7-8ff8-44d90433b08a.jpg)

**Comment by marmeladapk** [comment]
Please merge with #349

**Comment by jbqubit** [comment]
Or post that photo to #349 and close this duplicate Issue.
