### ISSUE TITLE
Sayma_AMC: SCANSTA dependence on MMC

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#449]
In https://github.com/m-labs/sinara/issues/448#issuecomment-352375182 @gkasprow pointed out 

> Anyway, the idea of connecting MMC to the JTAG switch (SCANSTA) it controls was not the best one...
It can literally cut the branch on which it sits.

The current state is that a misbehaving MMC can disable updating of MMC via JTAG. Resolution requires attaching an external JTAG cable. Is there a straightforward remedy? For example, using spare IO on FT4232 to control SCANSTA instead of MMC? For example, switching DDBUS to bit-bang mode when using JTAG and activating serial mode (MMC_CONSOLE) only when JTAG programming is done.

**Comment by jbqubit** [comment]
@gkasprow said
> you can do it [update MMC flash] via USB with some xmodem protocol

Does that work in the case that the MMC is completely corrupted?

**Comment by gkasprow** [comment]
@jbqubit yes, the bootloader is carved in stone and the only thing you need to upgrade the firmware is working serial port.
JTAG is yet another story and SCANSTA can be optionally configured with pin straps. But it's more convenient to use it in MMC controlled way.

**Comment by sbourdeauducq** [comment]
> spare IO on FT4232

FTDI GPIO is lousy with bugs and I recommend against it (or use the counterfeit chips, which have the bugs fixed).

**Comment by gkasprow** [comment]
The counterfeit chips has such feature that they get permanently locked while connected to Windows machine with recent FTDI drivers :) So FTDI recognizes and kills them :)

**Comment by jbqubit** [comment]
> the bootloader is carved in stone and the only thing you need to upgrade the firmware is working serial port.

Sounds like this concern is resolved if it is indeed straightforward to upgrade firmware using serial port.
