### ISSUE TITLE
Sayma RTM/AMC schematics review

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#45]
# Design Review: Sayma RTM and AMC

* Tracking issue: #45
* Milestone: [0.1rc1](../milestone/6)
* Commit ID: 06928c87
* Schematics PDF:
  * [Sayma_RTM.pdf](../raw/06928c87/ARTIQ_EE/Sayma_RTM.pdf)
  * [Sayma_AMC.pdf](../raw/06928c87/ARTIQ_EE/Sayma_AMC.pdf)

* Date started: 2016-11-01
* Retargetted: (fabc55eb -> 06928c87): 2016-11-07
* Date finished:

Everybody:
  * Do the review. Use [SchematicsReviewChecklist](../wiki/SchematicsReviewChecklist) as a guide.
  * [Create new issues](new?milestone=6&assignee=gkasprow) for problems/notes/errors/comments.
  * Add labels to the issues you file. At least add a priority/severity.
  * Assign it to the [0.1rc1](../milestone/6) milestone.

Will close this issue when the review is done.

**Comment by michallgaska** [comment]
Missing ground connections at sheet FPGA_XCKU040FFVA1156(FPGA Decoupling)

**Comment by gkasprow** [comment]
I committed newest version with reference designators and correct symbols which are paired with footprints. I did not fix bugs. Now project passes ERC, compiles so I will start component placement.

**Comment by jbqubit** [comment]
What type of tests are included in ERC?

**Comment by jbqubit** [comment]
@Jordens There's not been much activity on this approach to coordinating a design review. By my eye it doesn't provide enough structure or accounting. Please discuss with Greg how to divvy up the job and make use of e.g. Issues to increase activity.

**Comment by gkasprow** [comment]
> What type of tests are included in ERC?
>
>
> it depends how one configures it.
- power distribution, local/global nets
- hanging nets
- bus width and bus signals
- missing ports
- signals connected to power ports
- outputs shorted
- undriven inputs
and many, many others
I just passed very basic tests. Once the schematics are frozen, I will do
full diagnostics and cleanup things like aesthetic fonts, designator
placement, line widths..

**Comment by jordens** [comment]
@jbqubit That's an unacceptably vague and nebulous comment. By my eye the low activity means either "everybody is lazy or has no time" or "everything is good".
We have had the schematics to do the review since yesterday.
Please also give me a list of people how are reviewing something (other than WUT and M-Labs).

**Comment by hartytp** [comment]
@jordens the version of the schematics you link to on the wiki is now out of date.

**Comment by jordens** [comment]
@hartytp edited.

**Comment by jbqubit** [comment]
Commit ID: 06928c8 is now far in the past. Closing this Issue.
