### ISSUE TITLE
double front panel height of Kasli and VHDCI carrier

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#450]
All the IDC cables installed and stacked up exceed the current height of the front panel and bump into the next card.
![scables](https://user-images.githubusercontent.com/720864/34145627-e68fb46c-e4d1-11e7-98c1-e847c342fbe5.jpg)

**Comment by gkasprow** [comment]
You can mitigate it in 2 ways.
- install only lower part of IDC connector.
- add blind front panel.
I wouldn't make the 8HP panel because in many cases this would not be an issue.

**Comment by dhslichter** [comment]
It looks to me like even with just the lower part of the IDC connector installed you are pretty close to the maximum width of the front panel.  What are the nominal measurements there, @gkasprow?   Is it really not worth making an alternate front panel design which is 8 HP for those who'd rather have the extra room?

**Comment by gkasprow** [comment]
Well, we can do but this means that have to keep 2 version stocked...

**Comment by jordens** [comment]
I'd vote for 8hp Kasli. It is usually just one or two Kasli a per rack and 4hp horizontal for wiring etc. would be appreciated by me at least.

**Comment by dhslichter** [comment]
I second @jordens here, I think the 4 HP are worth it for having the wiring be a bit more manageable.  I imagine that @hartytp will want everything as narrow as possible, though.

**Comment by cjbe** [comment]
My vote is on keeping it 4HP:
If we make it 4HP and one wants more space for cabling, one can add a 4HP blanking plate (which are almost free). If instead we make it 8HP one has to crack out the bandsaw when pushed for space.

As an aside, I have been using the 4HP VHDCI carrier with 8 IDCs populated, and there is enough space if one does not use the strain relief clip (although there is very little excess space...)

**Comment by dtcallcock** [comment]
Can you just ship a blanking plate with each Kasli?  It would be cool if the blanking plate had some sick graphics on it.

**Comment by gkasprow** [comment]
Sure, we can. There are already COTS ones, but without graphics.

**Comment by jordens** [comment]
No. Seven ribbon cables on top of an IDC even without the strain relief dont fit. You'd have to unmount the filler panel each time. That's unneeded. And even with 8hp Kasli, there ist still plenty of space to fit a 32 channel NU Servo into a single crate.

**Comment by jbqubit** [comment]
OK. Look like consensus is to use blank 4U panel. Closing.

**Comment by jordens** [comment]
Nonsense. That was a 3:3 at best.

**Comment by dhslichter** [comment]
8HP

**Comment by hartytp** [comment]
Don't care either way is mine.

**Comment by jordens** [comment]
Let's err on the side of usability and make Kasli 8 HP wide. The only reason to have Kasli 4 HP wide would be density. I measured the height of various IDC connectors without and even without strain relief Kasli/VHDCI would be usable with 4 EEMs max. After that you are hitting the next panel when inserting/removing. Whether that's a filler panel or not does not matter: you would have to unmount the next panel as well each time you are trying to get at Kasli. Saving space in a system where you are only using half (VHDCI) or a third (Kasli) of the capabilities seems paradoxical. Once density becomes necessary, I'd recommend looking into populating the sub-rack from both sides. Then you can happily fill a single 19"/84 HP/3 U sub-rack with 4 Kaslis, 16 Urukuls, and 8 Samplers, get and get 64 channels of nu-servo while still having 4 HP unused on each side. **And** you would be able to mount/unmount Kasli...

**Comment by jbqubit** [comment]
I'm persuaded. 8HP sounds good to me. Does that tip the balance so we can close?

**Comment by gkasprow** [comment]
I changed both to 8HP..
