### ISSUE TITLE
Sayma RTM layout

### ISSUE THREAD

**Issue by cjbe** [m-labs/sinara#464]
Greg, can you give me an assembly diagram or something for Sayma RTM that will help me locate components during debugging? Thanks!

oops, wrong account -- sorry Chris!

**Comment by gkasprow** [comment]
@cjbe the easiest way is to install free viewer from Mentor.
You can get it from https://www.mentor.com/pcb/downloads/visecad-viewer/
if you have troubles getting it, I can share it on my dropbox

**Comment by hartytp** [comment]
Thanks!

**Comment by gkasprow** [comment]
There is *cce file dedicated for the viewer.
