### ISSUE TITLE
RGMII white wire patch HOWTO

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#484]
Thanks to the hard work of @gkasprow and @sbourdeauducq RGMII is more or less [working](https://github.com/m-labs/artiq/issues/854#issuecomment-358842622) on Sayma. This path requires a [white-wire modification](https://github.com/m-labs/artiq/issues/854#issuecomment-352244364) to Sayma_AMC. So far its been done in two boards. 

@gkasprow Please update your instructions on how to do this patch in this Issue. Do you have photos of what this looks like once complete? Are there any pitfalls we should avoid?

**Comment by gkasprow** [comment]
I'm not sure what white wire you are talking about.
I applied PHY clock connection on all boards

**Comment by sbourdeauducq** [comment]
RGMII RXCLK to clock-capable GPIO0.

**Comment by sbourdeauducq** [comment]
Note: On future PCB version, the RGMII RXCLK should be placed in the same bank as the other RGMII signals. The FPGA still doesn't like it too much when you are clocking a bank with another (or at least it doesn't like this particular combination of banks), and it still needs a special Vivado command (``CLOCK_DEDICATED_ROUTE BACKBONE``) to complete the routing.

**Comment by jbqubit** [comment]
@gkasprow The modification that will allow me to duplicate what you and @sbourdeauducq did to get RGMII working.

**Comment by gkasprow** [comment]
I'll update my board and make  microscopic photos with instructions.

**Comment by gkasprow** [comment]
@jbqubit 
The steps:
- cut the trace with sharp blade

![rxclockmod](https://user-images.githubusercontent.com/4325054/35398674-c9cf2f18-01f2-11e8-9b57-82dbb7a83466.png)

- solder thin insulated wire
![rxclockmod2](https://user-images.githubusercontent.com/4325054/35398698-d8929206-01f2-11e8-8197-acc47d708228.png)

- solder it to pin 1 of GPIO connector
![rxclockmod3](https://user-images.githubusercontent.com/4325054/35398713-e5110c2e-01f2-11e8-9f29-55a24c2e1861.png)

- secure the wire with thermal glue
![rxclockmod4](https://user-images.githubusercontent.com/4325054/35398727-edaa4d50-01f2-11e8-8cc8-7ad960565d13.png)
