### ISSUE TITLE
Sayma RTM FPGA debugging

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#49]
I propose that the second UART channel (currently "SoC") of the FTDI chip on AMC goes directly to a small header that can be connected to the RTM FPGA via an additional cable when the AMC/RTM is outside the crate. This can come useful to debug RTM FPGA transceiver problems.

**Comment by gkasprow** [comment]
We have 2 spare line in RTM connector. They can be used as UART or reserved
for future needs.


>

**Comment by sbourdeauducq** [comment]
Sounds good, in that case connect them to the FPGAs on each side and keep the two UART connections between the Ultrascale and the FTDI-chip. The Ultrascale could trivially connect a UART to the RTM and this gives a bit more flexibility.

**Comment by gkasprow** [comment]
OK, I will route them as diff pair.
For UART it doesnt make any difference but can be used for other higher speed purpose.
