### ISSUE TITLE
RTM 1V2 and 2V0 failure

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#496]
On one RTM I have, the P1V2 and P2V0 LEDs are off. This persists after power cycles. This is all the information I have for now.

**Comment by gkasprow** [comment]
please make sure that the transistor that is on the board edge, close to LEDs, that switches these LEDs on is not broken mechanically. I managed to break it by inserting the board to the chassis.
It is simply too close to the board edge.

**Comment by sbourdeauducq** [comment]
Yes. T7 is broken on that board.

**Comment by jbqubit** [comment]
So the power hasn't actually failed in this case, right? Its just the transistor for the LEDs? @gkasprow did you update layout?

**Comment by gkasprow** [comment]
It is on todo list.

**Comment by jbqubit** [comment]
Just looked at my RTMs too. Those LEDs are off and transistor is broken. Glad to hear this is easy to fix in Sayma 2.
