### ISSUE TITLE
Sayma_RTM power fails fail

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#500]
@sbourdeauducq said in #494
> I just noticed that sometimes some RTM power rails also fail (I have not opened a separate issue yet).

**Comment by hartytp** [comment]
@jbqubit this was #496 it's been resolved already (it was a known issue due to a transistor located too close to the edge of the RTM that can easily be nocked off).

**Comment by jbqubit** [comment]
Excellent! :)
