### ISSUE TITLE
After Sayma v2, deprecate  Sayma v1?  

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#508]
Sayma v2 will have different gateware than Sayma v1. M-Labs wants to know how to support this in the ARTIQ codebase going forward. Here's what I propose. 

- __now__
    - support for Sayma v1
- __Sayma v2 is available__ 
    - support for Sayma v1 maintained in codebase, only bug fixes are back-ported 
    - support for Sayma v2 
- __Sayma v2 works with ARTIQ__
    - Sayma v1 removed from codebase; last-good commit referenced in wiki
    - support for Sayma v2

**Comment by dhslichter** [comment]
Sounds good to me.
