### ISSUE TITLE
TTL SMA isolation from front panel

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#522]
In each SMA-DIO the two banks are supposed to be galvanically isolated, but the grounds of the SMA connectors are shorted by the front panel.
![ttl_sma_insul](https://user-images.githubusercontent.com/720864/37025850-c1e03c7c-2167-11e8-87b2-caa9086e5711.jpg)

**Comment by gkasprow** [comment]
Aren't there black shrinking tubes on the SMA connector installed?

**Comment by sbourdeauducq** [comment]
There are, but the nuts on the SMA connectors are resting directly on the varnished metal of the front panels. Even though the DC impedance between two banks that I measured is ~200k, this looks quite fragile. I was expecting some solid plastic washer like those on Urukul.

**Comment by gkasprow** [comment]
The front panel label is not conducting. 200k were placed intentionally to
discharge potential ESD. Plastic washers dont fit. I couldnt find smaller
ones that used in Urukul.

**Comment by hartytp** [comment]
>  I couldnt find smaller ones that used in Urukul.

I thought you were planning to 3D print these. Or did that work out too expensive?

**Comment by gkasprow** [comment]
I did dedicated one for Sayma RTM.
For SMA IO it's too expensive and the heat shrink tubes seem to work well.

**Comment by hartytp** [comment]
@gkasprow Sounds good. I was just curious!
