### ISSUE TITLE
DIO_BNC channels 4/5 and 6/7 swapped (J3/J4 swapped)

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#526]
* panels are ok
* termination switches are ok
* termination leds are ok
* J3 carrying IO4/5 and J4 carrying IO6/7 should swap positions

**Comment by gkasprow** [comment]
ups, I have added this to the SMA DIO errata instead of BNC DIO. Let's keep it here as independent issue

**Comment by gkasprow** [comment]
right.

**Comment by jordens** [comment]
#527
