### ISSUE TITLE
Sayma RTM: clock diagnostic outputs

### ISSUE THREAD

**Issue by hartytp** [m-labs/sinara#56]
@gkasprow If there is sufficient space on the RTM, please consider adding RF connectors (SMA/MMCX/whatever) on some of the unused outputs of clock fanout buffers, inc HMC704x (1 pair of connectors per fanout-buffer). These can be DNF by default, and would be useful for characterising/debugging the clock distribution network.

Don't worry if space is too tight though...

**Comment by sbourdeauducq** [comment]
I suppose those would not be on the front panel, right?

**Comment by hartytp** [comment]
Definitely not!

**Comment by gkasprow** [comment]
What abut UFL connectors?
I often mount them as high frequency testpoints
And they take very little space

**Comment by hartytp** [comment]
@gkasprow happy to use whatever connectors you prefer for this.

**Comment by gkasprow** [comment]
Add it as an issue with example signals specified.

**Comment by sbourdeauducq** [comment]
@gkasprow this is already an issue and @hartytp proposed "some of the unused outputs of clock fanout buffers, inc HMC704x".

**Comment by sbourdeauducq** [comment]
There are no unused outputs right now. But we can disconnect RTM_MASTER_AUX_CLK_* (aka FPGA_REF_CLK_*, see #63) which is the output that goes to the Artix-7 FPGA and probably is not useful, and put a pair of UFL connectors instead.
