### ISSUE TITLE
Logo aspect ratio in schematics

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#57]
Please keep the aspect ratio when resizing the logo, add blank space if needed.

**Comment by gkasprow** [comment]
What is exact aspect ratio? I will change the table.

**Comment by sbourdeauducq** [comment]
When you open the logo's image file, it has a certain width and a certain height. Both should be scaled by the same factor.

**Comment by gkasprow** [comment]
true:)
