### ISSUE TITLE
AMC_FABRIC_CLOCK on DAC/ADC transceivers

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#59]
* What is the purpose of AMC_FABRIC_CLOCK connected to MGTREFCLK0_224?
* If it is for clocking the ADC/DAC transceivers, it should move to MGTREFCLK0_225 or MGTREFCLK1_226 to reduce the imbalance in the number of quads that have to be crossed to drive the full set of transceivers.
* If it is for clocking the FAT_PIPE1 transceivers, it should move to MGTREFCLK1_228 so that no quad has to be crossed.

**Comment by gkasprow** [comment]
It is for FAT PIPE 1, fixed
