### ISSUE TITLE
GTPRX_CLK_IN_N/GTPTX_CLK_IN_N names are misleading

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#60]
There is no such thing as RX or TX reference clocks for transceivers, any reference clock can be equally used for TX or RX.

**Comment by gkasprow** [comment]
I know it, but there was request to route dedicated clock for Rx and Tx (ADC and DAC)

**Comment by gkasprow** [comment]
changed to GTP_CLK1_IN_N/P and GTP_CLK2_IN_N/P
