### ISSUE TITLE
Sayma v1 rework documentation

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#600]
In this issue I will document all rework that was done in rev1 and how they were applied in rev2. I will also document other changes to the design.

**Comment by gkasprow** [comment]
Slow start circuit for FMC 12V
new schematics - gray symbols were added
![obraz](https://user-images.githubusercontent.com/4325054/48788673-98cf6b00-eceb-11e8-9188-f751bdab74f0.png)

![sayma_amc_fmc_slow_start](https://user-images.githubusercontent.com/4325054/48788681-9ec54c00-eceb-11e8-9db8-a7d6a92adce5.jpg)

**Comment by gkasprow** [comment]
RTM slow start
![obraz](https://user-images.githubusercontent.com/4325054/48788771-d0d6ae00-eceb-11e8-8f37-7e87de5bace0.png)
![amc_rtm_slow_start](https://user-images.githubusercontent.com/4325054/48788823-eba92280-eceb-11e8-80e4-32ce363d70cf.jpg)

**Comment by gkasprow** [comment]
similar slow start circuit was added to RTM P3V3_MP switch

![obraz](https://user-images.githubusercontent.com/4325054/48790937-c4088900-ecf0-11e8-805b-ca83c2de2f87.png)

**Comment by gkasprow** [comment]
Main Payload power current limit was added. Before it was just 0.02R resistor
![obraz](https://user-images.githubusercontent.com/4325054/48793066-2021dc00-ecf6-11e8-897f-7e0ff5134638.png)


![amc_payload_i_lim](https://user-images.githubusercontent.com/4325054/48792964-e2bd4e80-ecf5-11e8-89fb-310052b136a4.jpg)

**Comment by gkasprow** [comment]
Exar chip GPIO0 and PSIO2 pins were swapped. GPIO pins are push-pull while PSIO pins are open drain. So PSIO is better suited as input and GPIO as output.
![obraz](https://user-images.githubusercontent.com/4325054/48793694-1305ec80-ecf8-11e8-986d-dbdb2d31e255.png)

![amc_exar_gpio0_psio2](https://user-images.githubusercontent.com/4325054/48793948-e0a8bf00-ecf8-11e8-93eb-e924472bc4f0.jpg)

**Comment by gkasprow** [comment]
Missing pulldown resistors for LVPECL outputs were added. LVDS version can be used as well but its availability is worse.
![obraz](https://user-images.githubusercontent.com/4325054/48793883-a6d7b880-ecf8-11e8-853a-d839d247b0d7.png)

![osc_pulldowns](https://user-images.githubusercontent.com/4325054/48793990-f74f1600-ecf8-11e8-85e5-1d6614b02df3.jpg)

**Comment by gkasprow** [comment]
swapped IO direction control was fixed
![obraz](https://user-images.githubusercontent.com/4325054/48794114-472ddd00-ecf9-11e8-8d1d-5004200ab2ef.png)

![io_dir_ctrl](https://user-images.githubusercontent.com/4325054/48794134-544acc00-ecf9-11e8-8c88-4c3f7c0deab1.jpg)

**Comment by gkasprow** [comment]
Too low VCCINT voltage, drop during high current consumption. Rfb selected to give 0.95V. R508 installed to compensate voltage drop.
![obraz](https://user-images.githubusercontent.com/4325054/48796655-7ac03580-ed00-11e8-9b83-66ed78fcc87d.png)
![vccint_rrb](https://user-images.githubusercontent.com/4325054/48796688-8ca1d880-ed00-11e8-996d-14a113da676f.jpg)

R508
![vccin_r315](https://user-images.githubusercontent.com/4325054/48806175-d34ffc80-ed19-11e8-8816-c74a665041a5.jpg)

**Comment by gkasprow** [comment]
Ethernet issues:

Ethernet PHY RX clock
![2018-01-25 16 56 20](https://user-images.githubusercontent.com/4325054/49117471-13c2f380-f2a1-11e8-8a74-baadf9c97523.jpg)



![2018-08-09 13 19 37](https://user-images.githubusercontent.com/4325054/48797743-531e9c80-ed03-11e8-9218-3e4be4a9a79d.jpg)
![2018-08-09 13 01 17](https://user-images.githubusercontent.com/4325054/48797773-6467a900-ed03-11e8-9416-bd27ceb250e0.jpg)

need radical solutions.
First, correct RX_CLK pin on FPGA. We won't need TCLKC_D so can use this GC for RX clock.
![obraz](https://user-images.githubusercontent.com/4325054/48804942-46f00a80-ed16-11e8-9c7b-3897dcb471a0.png)



Second, disconnect from MMC chip. There are no PHYs that support 100M<-> 1G speed translation.
So we will stick with popular, available and well known 88E1512.
The MMC will be connected only to MDIO bus, just in case. ETH1_MII name is changed to PHY_CFG

![obraz](https://user-images.githubusercontent.com/4325054/48798486-08058900-ed05-11e8-9552-930b8e8148ea.png)

We also get rid of the Mux and PHY schematic gets simplified a lot.

**Comment by gkasprow** [comment]
PHY configuration is copied from [Lattice devkit](https://www.mouser.com/pdfdocs/Lattice_EB98.PDF).

**Comment by sbourdeauducq** [comment]
> The MMC will be connected only to MDIO bus,

Just connect to FPGA.

**Comment by gkasprow** [comment]
The new PHY is much simpler, simple supply, no external oscillator and I used it already.
![obraz](https://user-images.githubusercontent.com/4325054/48806108-9f74d700-ed19-11e8-9546-5dff7bbbdeb7.png)

**Comment by gkasprow** [comment]
MMC reset during USB plugging was fixed by adding RCD circuit. It was verified on AFCZ board.
![obraz](https://user-images.githubusercontent.com/4325054/48806622-2b3b3300-ed1b-11e8-9a3d-72f597a27073.png)
Flashmagic bootloader mode can be disabled using DIP switch
![obraz](https://user-images.githubusercontent.com/4325054/48807140-e912f100-ed1c-11e8-9fb4-635f2e7a0fd5.png)

It was tested on AFCZ



before wire jumper was used

![amc_t23_gnd_mmc reset](https://user-images.githubusercontent.com/4325054/48806588-13fc4580-ed1b-11e8-87d8-091fc89c5df1.jpg)

**Comment by gkasprow** [comment]
MMC JTAG wac blocked by SCANSTA. RCT circuit was added to disable SCANSTA chip when the MMC programmer plug is inserted.

![mmc jtag scansta disable](https://user-images.githubusercontent.com/4325054/48807221-27101500-ed1d-11e8-999c-3c3a4e49e313.jpg)

![amc scansta disable](https://user-images.githubusercontent.com/4325054/48807242-38592180-ed1d-11e8-8000-fd8d47fe89d2.jpg)

Analog switch was added that cuts SCANSTA JTAG access when the JTAG plug is inserted. It was verified on AFCZ 

![obraz](https://user-images.githubusercontent.com/4325054/48807267-5030a580-ed1d-11e8-99f5-d109df405e57.png)

**Comment by gkasprow** [comment]
LTC6957 had SD pins tied to VCC instead of GND
![20180807_170743](https://user-images.githubusercontent.com/4325054/48807322-7f471700-ed1d-11e8-982a-bd40a5c3a161.jpg)
![obraz](https://user-images.githubusercontent.com/4325054/48807349-9554d780-ed1d-11e8-9bd1-70504eb25213.png)

SMA clock output was connected to LTC6957 output and recovered clocks delivered to FPGA had phase shift. IT was fixed by connecting SMA output to the Si5324s chip directly.

**Comment by gkasprow** [comment]
SCANSTA did not change master port when USB was plugged after power on. Jumper had to be placed on JTAG connector pins to keep it in permanent USB mode.

**Comment by sbourdeauducq** [comment]
This SCANSTA caused a relatively low number of problems (by Sayma standards), but do we really need it?

**Comment by hartytp** [comment]
@gkasprow which change fixes USB JTAG so that no jumper is needed?

**Comment by gkasprow** [comment]
Instead of SCANSTA we would have to use discrete JTAG muses and potentially add issues. @hartytp This was fixed by another line routed to MMC so it knows state of the USB JTAG and resets SCANSTA. I will explain it later on.

**Comment by sbourdeauducq** [comment]
On the KC705, there is just a switch that closes to connect TDI and TDO when the FMC is unplugged. It does cause pesky issues with improperly designed FMCs that leave TDI/TDO open (as the leakage through the switch is enough for some data to go through, but with some random corruption). However, this is a simple and low-cost design that is easy to understand - the only difficulty is you need to watch out for the above-mentioned problem - and not some Rube-Goldberg programmable mess in a BGA package.
AFAICT the only places where we need JTAG switching is for the FMC and the RTM. I can't be bothered with µTCA JTAG which - like everything else in µTCA - sounds expensive, temperamental, overly complicated and generally hopeless; µTCA can't even power up the board properly. For remote board updates, better send them over DRTIO and have the ARTIQ firmware rewrite the flash and reboot the FPGA; all the difficult code is already there, and my experience with the Xilinx ICAP has been surprisingly positive.

**Comment by gkasprow** [comment]
If we are going to support remote update over RTIO, I can remove the SCANSTA entirely. The switches can be also controlled via MMC as it does with SCANSTA.

**Comment by sbourdeauducq** [comment]
Currently there is no funding for DRTIO firmware updates, but there is also no funding for µTCA firmware updates. The former is much easier and lower-cost to implement, and would also support Kasli.

**Comment by gkasprow** [comment]
uTC firmware update is performed by NAT MCH + Jtag Switch Module. At least my coleagues in DESY use it in such way. Personally I never tested it. I used Vadatech JSM so far and that's why implemented switches.
But we can keep access to the AMC JTAG using muxes, without using SCANSTA chip.
On AFCZ board I added SCANSTA in both BGA and TQFP package because had issues with availability.
It can be done in the same way as on KC705, with ability to overdrive FMC and RTM detect pins by MMC. AMC access can be performed by additional mux. In this way we keep simplicity. We loose ability to control JTAG chain via JTAG commands which worked quite nicely in AFCK board, but once we are able to force working configuration with MMC, I don't care.

**Comment by gkasprow** [comment]
The RTM FPGA config pins were connected 0 0 1, it should be 1 1 1.
![2018-07-19 15 47 29](https://user-images.githubusercontent.com/4325054/49046650-1bb56180-f1d5-11e8-9774-102426abd39a.jpg)
Now we have 
![obraz](https://user-images.githubusercontent.com/4325054/49046668-2c65d780-f1d5-11e8-9b0a-4fdd4f80d194.png)

**Comment by gkasprow** [comment]
RTM FPGA config pins were swapped. DIN is not data in but D00_MOSI.
HW fix:
![rtm_fpga_swapped config pins](https://user-images.githubusercontent.com/4325054/49046903-00972180-f1d6-11e8-9ee9-b53bee1b5cbc.jpg)
![rtm_fpga_cfg_pins_dac](https://user-images.githubusercontent.com/4325054/49046942-1efd1d00-f1d6-11e8-9375-0cb9c7c1995d.jpg)

Schematic fix:
![obraz](https://user-images.githubusercontent.com/4325054/49046963-2de3cf80-f1d6-11e8-8bb0-5d3c658b57fb.png)

**Comment by gkasprow** [comment]
Missing connection of VTT with SVDD12
![vtt_1 2v1](https://user-images.githubusercontent.com/4325054/49047137-c5e1b900-f1d6-11e8-9ade-aaf2d1209339.jpg)
![vtt_1 2v2](https://user-images.githubusercontent.com/4325054/49047140-c712e600-f1d6-11e8-88b1-eb23120c6237.jpg)

fix:
![obraz](https://user-images.githubusercontent.com/4325054/49047180-e447b480-f1d6-11e8-8865-486a9cbd6576.png)

**Comment by gkasprow** [comment]
Broken feedback loop for DC/DC converters
![2018-08-09 14 37 56](https://user-images.githubusercontent.com/4325054/49047373-8e274100-f1d7-11e8-805d-c43dd513e2a9.jpg)

The VFB resistors must go to GND.

![obraz](https://user-images.githubusercontent.com/4325054/49047545-0ee63d00-f1d8-11e8-818b-11c92040d757.png)

**Comment by gkasprow** [comment]
IC34 SD pins should be grounded.
![rtm_ic34_sdpins](https://user-images.githubusercontent.com/4325054/49047641-5f5d9a80-f1d8-11e8-890d-db2f7cffbca8.jpg)
![obraz](https://user-images.githubusercontent.com/4325054/49047667-73a19780-f1d8-11e8-8d03-7f69408afaf4.png)

**Comment by gkasprow** [comment]
not enouth current for SVDD12
![rtm_1 2v dac2](https://user-images.githubusercontent.com/4325054/49047954-63d68300-f1d9-11e8-8e02-2845030ba455.jpg)
![rtm_1 2v dac1](https://user-images.githubusercontent.com/4325054/49047955-63d68300-f1d9-11e8-9d73-878889eee9af.jpg)

fix - bridge 2 LDOs together with 20mOhm resistors
![obraz](https://user-images.githubusercontent.com/4325054/49048137-05f66b00-f1da-11e8-9126-d1aa3048ae85.png)

**Comment by gkasprow** [comment]
HMC7043 not connected RSV lines, reset line should be tied to VCC to keep it in reset state until FPGA initialises it.
![rtm_7044_rsv and reset](https://user-images.githubusercontent.com/4325054/49048544-6a65fa00-f1db-11e8-86ae-a90c699b6fd9.jpg)

fix
![obraz](https://user-images.githubusercontent.com/4325054/49048519-515d4900-f1db-11e8-90bc-5e4ab6d4b696.png)

**Comment by gkasprow** [comment]
Fix power sequencing of negative SEPIC converter -  by addin 1uF cap to SS to make sure negative converter starts after positive one.
![rtm n6v slow start](https://user-images.githubusercontent.com/4325054/49048801-6f777900-f1dc-11e8-80a9-cac8ca56dc8c.jpg)
fix
![obraz](https://user-images.githubusercontent.com/4325054/49048808-7a320e00-f1dc-11e8-997c-e702fe4c66b9.png)

**Comment by gkasprow** [comment]
Missing DAC output termination and input clock termination
![2017-07-13 12 30 06](https://user-images.githubusercontent.com/4325054/49048879-cda45c00-f1dc-11e8-8165-89eda1837c18.jpg)

Added 100R terminators to SYSREF and CLK and 49R9 to outputs.
![obraz](https://user-images.githubusercontent.com/4325054/49049573-d3e80780-f1df-11e8-8725-f620adbcc93a.png)

**Comment by gkasprow** [comment]
add 10k pulldown on PLL chip CLK and SEN lines to make sure that logic state is well defined and FPGA can setup correct SPI protocol.
![rtm_hmc830_sclk_10k gnd](https://user-images.githubusercontent.com/4325054/49049929-663cdb00-f1e1-11e8-98d7-63e5b4f761b5.jpg)
fix
![obraz](https://user-images.githubusercontent.com/4325054/49049939-73f26080-f1e1-11e8-98f5-400c6868c52d.png)

**Comment by gkasprow** [comment]
Wrong schematic symbol of interdigitated capacitors
![2017-10-09 14 55 54](https://user-images.githubusercontent.com/4325054/49050422-a3a26800-f1e3-11e8-9feb-0d25ed0c9e2f.jpg)

Caps had to be soldered one side only.
Pins 5-8 were connected in reversed order
fix:

![obraz](https://user-images.githubusercontent.com/4325054/49116034-a6ad5f00-f29c-11e8-94fb-3022faf4510c.png)

**Comment by sbourdeauducq** [comment]
> HMC7043 not connected RSV lines,

Thankfully, we're not using this chip anymore.

**Comment by gkasprow** [comment]
So, will we switch to HMC7044?

**Comment by hartytp** [comment]
> So, will we switch to HMC7044?

No, we will remove the HMC7043 entirely and replace it with a fanout + DFF + delay line. 

See here: https://github.com/sinara-hw/sinara/issues/594

**Comment by hartytp** [comment]
NB there is a list of changes for Sayma v2.0 here https://github.com/sinara-hw/sinara/milestone/22

**Comment by gkasprow** [comment]
ACK

**Comment by gkasprow** [comment]
Daisychain FPGA configuration did not work for unknown reason, so we switched to direct config of RTM FPGA by AMC FPGA. Resistors must replaced:
![2018-08-09 13 07 28](https://user-images.githubusercontent.com/4325054/49116745-deb5a180-f29e-11e8-8520-b1ab7d34505a.jpg)
![2018-08-09 13 07 43](https://user-images.githubusercontent.com/4325054/49116754-e5441900-f29e-11e8-8fef-531eedd538d5.jpg)

So we make daisychain connection DNP, we can also remove it later on
![obraz](https://user-images.githubusercontent.com/4325054/49117204-3accf580-f2a0-11e8-8919-20fb6f365d39.png)

and we mount
![obraz](https://user-images.githubusercontent.com/4325054/49117310-841d4500-f2a0-11e8-8d93-7386efe716e4.png)

**Comment by gkasprow** [comment]
SCANSTA chip blocks MMC JTAG even when port is inactive. The simplest way was to disable the SCANSTA chip entirely when MMC JTAG plug was detected. 2x 10k resistors, 100nF capacitor + MOSFET are needed.
![2017-07-13 13 48 38](https://user-images.githubusercontent.com/4325054/49117783-3f92a900-f2a2-11e8-9b44-e599df590ea4.jpg)

![obraz](https://user-images.githubusercontent.com/4325054/49117733-08bc9300-f2a2-11e8-881a-b24b69646551.png)
The SCANSTA_DISABLE goes instead of R29
![2017-07-13 13 48 48](https://user-images.githubusercontent.com/4325054/49117759-2be74280-f2a2-11e8-9f3e-781c6a48ec0d.jpg)

**Comment by gkasprow** [comment]
SCANSTA fails to switch to internal mode when USB is plugged after board was powered on. Simple solution is jumper on cable detect line.
![2018-08-09 13 06 03](https://user-images.githubusercontent.com/4325054/49117850-749efb80-f2a2-11e8-8190-d8dc23e86e36.jpg)

On rev 2 new JTAG switching scheme will be used.

**Comment by hartytp** [comment]
Closing as I don't think there will be any new rework for Sayma v1.0
