### ISSUE TITLE
newly created components

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#605]
New components added to Sayma boards:
Metlino, Sayma:
88E1512-XX-NNP2I000
LMK61E07-SIAT
549CBAC000112ABG

BaseMod
LTC2324CUKG-16#PBF

**Comment by atcher0** [comment]
Verified components (schematic symbol only):
- [x] 88E1512-XX-NNP2I000
- [x] LMK61E07-SIAT
- [x] 549CBAC000112ABG

**Comment by jbqubit** [comment]
Thanks @atcher0! Remains for @marmeladapk to check BaseMod symbol for this HT1.5 item.

**Comment by gkasprow** [comment]
Sayma RTM
HMC1060LP3E
ADF4356BCPZ
MC100EP31DTG
NB6L295MNG
ADCLK948BCPZ
XC7A35T-1CSG325
LTC6957IDD-1#PBF
W2L16C473MAT1S
TPSM84824MOLR

**Comment by atcher0** [comment]
Sayma RTM verified components (schematic symbol only):
- [x] HMC1060LP3E
- [x] ADF4356BCPZ
- [x] MC100EP31DTG
- [x] NB6L295MNG
- [x] ADCLK948BCPZ
- [x] XC7A35T-1CSG325
- [x] LTC6957IDD-1#PBF
- [ ] W2L16C473MAT1S -> lack of pin assigment information in datasheet (?)
- [x] TPSM84824MOLR

**Comment by marmeladapk** [comment]
W2L16C473MAT1S should be fine since + and - pins are alternately (which wasn't the case in v1.0 schematics). It's also connected this way on devkit (altough pin 1 is - in their schematics).

**Comment by gkasprow** [comment]
v1.0 schematics had bug in pin assignment of W2L16C473MAT1S

**Comment by marmeladapk** [comment]
All components listed here were checked.
