### ISSUE TITLE
rename FPGA_*xD and SoC_*xD 

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#61]
I am talking about the signals that go to the USB UART chip.

There is no SoC/FPGA distinction, in fact the typical use for those UARTs will be one for the Ultrascale FPGA and one for the Artix FPGA. I propose renaming them to PRI_UART_*xD and AUX_UART_*xD.

**Comment by jordens** [comment]
or `{AMC,RTM}_UART_*` but not `{FPGA,SoC}_UART_*`

**Comment by sbourdeauducq** [comment]
The AUX UART is not necessarily for RTM (which is why it goes through the KU FPGA), it is just how we envision to use it right now.

**Comment by jordens** [comment]
Ack. Then maybe just `UART1_` and `UART2_`. But anything is good.

**Comment by gkasprow** [comment]
done
