### ISSUE TITLE
RTM UART link needs to be bidirectional

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#62]
As far as I can tell, there is only one pair USR_UART_N/P between the AMC and RTM. We need one pair for TX and one pair for RX - or go single-ended if there aren't enough pins.

**Comment by sbourdeauducq** [comment]
This UART link will operate at a low speed (115kbps) so we can have a slow slew rate to reduce EMI/SI problems with single-ended signaling.

**Comment by sbourdeauducq** [comment]
RTM_FPGA_GTP_CLK can be removed as we can use the CDR + the Si5324 on the RTM side, this makes space for another UART pair.

**Comment by gkasprow** [comment]
This pair is routed as diff signal but can be used as 2 single ended signals for slow UART.
We can also use it as high speed LVDS

**Comment by sbourdeauducq** [comment]
I am fine with that solution.

**Comment by jbqubit** [comment]
Can this be closed?

-------
Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil

**Comment by sbourdeauducq** [comment]
I'd rather keep all those open until @gkasprow posts a new version of the schematics that includes the fix.

**Comment by gkasprow** [comment]
fixed
