### ISSUE TITLE
clock length matching

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#64]
When doing the layout, make sure that each SYSREF is matched to **its** CLK (a.k.a. DEVICECLK) to better than 100 ps.

**Comment by gkasprow** [comment]
What other lines should be matched?
DAC - mezzanine connector between channels
ADC - mezzanine connector between channels
JESD204B not necessary

**Comment by jordens** [comment]
* differential wire length matching (positive to negative): required
* I/Q wire length matching (the pair of channels to/from each mezzanine): yes, if possible
* matching any two mezzanines: nice to have
* ADC-to-DAC length matching: not necessary
* JESD204B links: only differentially length matched

**Comment by sbourdeauducq** [comment]
Matching between the RTM_FPGA_GTP_Rx* and between the RTM_FPGA_GTP_Tx* is also desirable, but not strictly necessary (we can have gateware to compensate, or use only one line to begin with).

**Comment by jbqubit** [comment]
@gkasprow  who on your team is responsible for Sayma layout? I'd like to assign them this and other layout related items.

**Comment by gkasprow** [comment]
It's me and Michal. Samer will do all SI verification

>
>

**Comment by gkasprow** [comment]
Yes.
