### ISSUE TITLE
RTM<->AMC transceiver link electrical compatibility

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#72]
Does the Artix-7 CML play nice with the Ultrascale LVDS, or do we need level converters?

**Comment by gkasprow** [comment]
No level translation is needed in AC-coupled mode
http://www.ti.com/lit/an/scaa059c/scaa059c.pdf

**Comment by sbourdeauducq** [comment]
OK, what translator chips are you going to use?
Those chips should be on the AMC side, as they are slower (<=2Gbps) than the Artix transceivers but faster than the KU IOSERDES. This way we don't introduce any additional speed limitation, in case we want to plug the RTM to some other card in the future.

**Comment by gkasprow** [comment]
Are you sure that translators are needed? Do you want to DC-couple them?

**Comment by sbourdeauducq** [comment]
Ah sorry, I misread and thought they were needed. AC coupling is fine.
