### ISSUE TITLE
Metlino access to MTCA MLVDS

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#76]
Do we have any plans to use MLVDS bus?
In MTCA.4 standard it connects all AMC boards together with 8x bidir MLVDS bus (Ports 17..20).
New Schroff backplanes will have  MLVDS bus routed to MCH, Tongue 2. There are some unused pins.
I can just place ordinary goldpin connector on Metlino in such way that in future we can make Tongue2 board that supports such functionality.
Would such bus be useful for ARTIQ? Distribution of some triggers, resets, interlocks, time stamps...
Some ideas?

**Comment by jordens** [comment]
I can't think of anything anything that would be generically useful without leading to a complexity nightmare.

I can see it being useful for bigger control loops (PIDs split between Sayma cards) without Metlino involvement but the point-to-point links on port 12-13 seem better suited for that.

**Comment by gkasprow** [comment]
OK, so I will use these FPGA IOs for Fabric E routing
