### ISSUE TITLE
allaki analog mezzanine: input protection

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#84]
In #38 it was decided that ESD protection should go on the mezzanine boards. For example ESD Protection Diodes with Transient Voltage Suppressor (TVS). Such ESD protection is missing from #81. Should it be there? If so which component? @jordens @hartytp @dhslichter @sbouhabib

**Comment by gkasprow** [comment]
we discussed that TVS cause signal distortion and that's why Schottky diodes were used.
I don't thing somebody is going to replace mezzanines while the AMC board is working so no protection diodes on IO lines were used.

**Comment by jordens** [comment]
I am uncertain why distortion is relevant for the DC coupled path that we are shooting for. But if the input impedance is large and upstream ESD diodes should be sufficient.

**Comment by jbqubit** [comment]
OK.
