### ISSUE TITLE
uRFB connectors named but not connected 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#86]
11/23/2016 schematic for Sayma RTM motherboard

- on p1 (Sayma_RTMu) RFB_DAC_CLK_IN from uRFB_DAC_CLK_IN is not connected
- on p1 uRFB_REF_CLK_IN appears on uRFB Connectors but doesn't connect to anything

------
Sayma RTM connections to RF backplane. 
- uRFB_REF_IN (from RADIALL connector, single-ended RF connector)
    - connected to CLK0 of ADCLK948
- uRFB_DAC_CLK_IN (from RADIALL connector, differential)
    - not connected
- REFSYNCIN (from ERNI connector, differential)
    - connected to RFSYNCIN on HMC7043
- uRFB_REF_CLK_IN (from ERNI connector, single-ended RF connector)
    - not connected
- uRFB_CLK_IN 
    - connected to CLK0 of ADCLK948

**Comment by hartytp** [comment]
@jbqubit We use one of uRFB_REF_IN or uRFB_REF_CLK_IN as our backplane 100MHz source. The choice is made by populating either C658 & C659 or R238 & R239. In the current version of the schematic, we have made the decision to use uRFB_REF_IN by default (as @sbouhabib was worried about the Radiall connector's high-frequency performance), so C658 & C658 are given as DNP.

**Comment by jbqubit** [comment]
OK. Thank makes sense for uRFB_REF_CLK_IN. 

> on p1 (Sayma_RTMu) RFB_DAC_CLK_IN from uRFB_DAC_CLK_IN is not connected

What about RFB_DAC_CLK_IN?

**Comment by gkasprow** [comment]
It is optionally routed to placeholder for balun and 2 SMP connectors.
In this way we can use external DAC clock generator in eRTM15 and on every Sayma install 2 SMP-SMP RA jumpers that connect balun output with HMC7043 input

**Comment by jbqubit** [comment]
I like this idea. But please update schematic so that this is clearer.
