### ISSUE TITLE
HMC830 PLL feedback component values

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#87]
11/23/2016 schematic for Sayma RTM motherboard

On p1 (Clock_Distribution_PLL) HMC830 PLL feedback component values are missing. @weidaZhang please supply.

It appears @weidaZhang has not accepted invitation to join the github sinara repository.

**Comment by hartytp** [comment]
@jbqubit Already posted in comments to #75. This is also listed as part of #88
