### ISSUE TITLE
allaki analog mezzanine: repository name cleanup

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#92]
- [x] Why is there both AFE_mezzanine and Sayma_Mezzanine? 
- [ ] Update m-labs/sinara/blob/master/README.rst to indicate high level view of what's in ARTIQ_EE

Refactoring:
- [ ] m-labs/sinara/Sayma_Mezzanine should be moved to m-labs/sinara/ARTIQ_EE/PCB_Sayma_mezzanine_allaki

- [ ] Since clock mezzanine could find application on both Sayma RTM and on RF_backplane distribution board, m-labs/sinara/Clock_Mezzanine should be moved to m-labs/sinara/ARTIQ_EE/PCB_mezzanine_clock

**Comment by gkasprow** [comment]
AFE_Mezzanine is simple test board and template for more complex mezzanines.
ArtiQ_EE is set of boards including Metlino. EE means Expdition Enterprise while mezzanines are done in Altium.

**Comment by jbqubit** [comment]
I've updated README.md.  https://github.com/m-labs/sinara/commit/766b4147f5ebf12e9818f8aa8a937d3c5b7d622c For consistency how about refactoring as in this commit? It foreshadows other analog mezzanine boards based on the same template.

**Comment by jbqubit** [comment]
Thanks for cleaning this up. Looks like there are still some stray files
Clock_Mezzanine/.DXF
AFE_Mezzanine/AFE_mezzanine.*

**Comment by gkasprow** [comment]
They have to be removed manually because were added via web interface

**Comment by gkasprow** [comment]
done
